### ISSUE TITLE
anvil error in open_multifile_dataset

### ISSUE THREAD

**Issue by mark-petersen** [MPAS-Dev/MPAS-Analysis#125]
On anvil, ./run_analysis.py always ends with:
```
File "...mpas_analysis/shared/generalized_reader/generalized_reader.py", line 126, in open_multifile_dataset
...
ValueError: invalid literal for int() with base 10: ''
```
We are not able to run MPAS-Analysis on anvil at this time.

**Comment by mark-petersen** [comment]
@vanroekel was getting this same error message.  Here it is in full:
```
blogin2 $ pwd
/home/mpeterse/repos/MPAS-Analysis/develop_170302
blogin2 $ git log --graph --oneline -n 3
*   c016aac Merge remote-tracking branch 'xylar/MPAS-Analysis/fix_oceanStreams_in_seaIceTimeseries' into develop
|\
| * 18503e9 Fix bug in sea ice analysis with oceanStreams
|/
*   9ff0c58 Merge fix_config_parser_bool

blogin2 $ ./run_analysis.py anvilconfig

Plotting OHC time series...
Reading files /lcrc/group/acme/jwolfe/acme_scratch/20170221.beta0.GMPAS-IAF.T62_oECv3.anvil/run/mpaso.hist.am.timeSeriesStatsMonthly.0001-01-01.nc through /lcrc/group/acme/jwolfe/acme_scratch/20170221.beta0.GMPAS-IAF.T62_oECv3.anvil/run/mpaso.hist.am.timeSeriesStatsMonthly.0004-01-01.nc
  Read in depth and compute specific depth indexes...
  Load ocean data...
Traceback (most recent call last):
  File "./run_analysis.py", line 259, in <module>
    analysis(config)
  File "./run_analysis.py", line 154, in analysis
    variableMap=oceanVariableMap)
  File "/blues/gpfs/home/mpeterse/repos/MPAS-Analysis/develop_170302/mpas_analysis/ocean/ohc_timeseries.py", line 114, in ohc_timeseries
    endDate=endDate)
  File "/blues/gpfs/home/mpeterse/repos/MPAS-Analysis/develop_170302/mpas_analysis/shared/generalized_reader/generalized_reader.py", line 126, in open_multifile_dataset
    decode_times=False, concat_dim='Time')
  File "/home/mpeterse/miniconda2/lib/python2.7/site-packages/xarray/backends/api.py", line 509, in open_mfdataset
    datasets = [preprocess(ds) for ds in datasets]
  File "/blues/gpfs/home/mpeterse/repos/MPAS-Analysis/develop_170302/mpas_analysis/shared/generalized_reader/generalized_reader.py", line 250, in _preprocess
    iselValues=iselValues)
  File "/blues/gpfs/home/mpeterse/repos/MPAS-Analysis/develop_170302/mpas_analysis/shared/mpas_xarray/mpas_xarray.py", line 253, in preprocess
    referenceDate='0001-01-01')
  File "/blues/gpfs/home/mpeterse/repos/MPAS-Analysis/develop_170302/mpas_analysis/shared/mpas_xarray/mpas_xarray.py", line 469, in _parse_dataset_time
    referenceDate=referenceDate)
  File "/blues/gpfs/home/mpeterse/repos/MPAS-Analysis/develop_170302/mpas_analysis/shared/mpas_xarray/mpas_xarray.py", line 494, in _parse_dataset_time
    calendar=calendar)
  File "/blues/gpfs/home/mpeterse/repos/MPAS-Analysis/develop_170302/mpas_analysis/shared/timekeeping/utility.py", line 228, in string_to_days_since_date
    dates = [string_to_datetime(string) for string in dateString]
  File "/blues/gpfs/home/mpeterse/repos/MPAS-Analysis/develop_170302/mpas_analysis/shared/timekeeping/utility.py", line 109, in string_to_datetime
    _parse_date_string(dateString, isInterval=False)
  File "/blues/gpfs/home/mpeterse/repos/MPAS-Analysis/develop_170302/mpas_analysis/shared/timekeeping/utility.py", line 479, in _parse_date_string
    second = int(hms)
ValueError: invalid literal for int() with base 10: ''
```

**Comment by mark-petersen** [comment]
@milenaveneziani worked on this with me.  We thought it might be a recent commit, so we tried these three versions, from Mar 1, Feb 16 and Feb 9.  All produce exactly the same error:
```
*   c016aac Merge remote-tracking branch 'xylar/MPAS-Analysis/fix_oceanStreams_in_seaIceTimeseries' into develop

*   3d1bd37 Merge remote-tracking branch 'xylar/MPAS-Analysis/variable_mapping_reorg' into 

*   3cce857 Merge remote-tracking branch 'xylar/MPAS-Analysis/config_reorg' into develop
```

**Comment by mark-petersen** [comment]
We also tried updating and changing some packages in python on anvil.  I installed my own python and compared with the packages on wolf.  

I installed the packages recommended here:
https://acme-climate.atlassian.net/wiki/display/OCNICE/Anaconda+Python+2.7+on+LANL+HPC%2C+ALCF%2C+OLCF%2C+LLNL+AIMS%2C+and+NERSC
i.e., these:
```
conda install -c scitools  -c https://conda.anaconda.org/opengeostat numpy scipy matplotlib ipython notebook netCDF4 progressbar vtk cartopy xarray dask bottleneck pyevtk numexpr basemap jsonschema yaml lxml mkl bokeh chest hdf5 libnetcdf libxml2 shapely flake8 pandas pytest pyyaml sphinx heapdict sphinx_rtd_theme
```
We tried adding these two:
```
blogin2 $ conda install anaconda dask=0.14.0
blogin2 $ conda install -cinstall -c conda-forge nco=4.6.4
```
but always get the same error.

**Comment by milenaveneziani** [comment]
@mark-petersen, @pwolfram and I found what caused this problem (pinging @vanroekel as well): since write_at_restart for `timeSeriesStats` was `on` for the particular run that we were trying to analyze on anvil, some of the January files had two time steps instead of 1. The analysis expects 1 monthly record for each monthly file, so it broke. The solution is to change back `write_at_restart=.false.` for both MPAS-O and MPAS-SI timeSeriesStats AM's in ACME default namelist files.

**Comment by xylar** [comment]
My understanding is that this turns out not to be an issue with MPAS-Analysis.  If that is correct, can we close the issue?

**Comment by mark-petersen** [comment]
This error is unrelated to Anvil.  We had set
```
 config_am_timeseriesstatsmonthly_write_on_startup = .true.
```
The result is that, on every restart, the first `mpaso.hist.am.timeSeriesStatsMonthly.*.nc` file has one entry of 45 minute duration, and a second for the rest of the month.  I think this is because of the coupling lag.

I am closing this issue and writing a more specific issue #126 to ask for better error handling here.
