### ISSUE TITLE
Corrupted climatology cache 

### ISSUE THREAD

**Issue by pwolfram** [MPAS-Dev/MPAS-Analysis#182]
If the calculation is interupted prematurely, for whatever reason, an error can result if the cache is not purged:

```
┌─[pwolfram][wf-fe1][~/MPAS-Analysis][08:24][±][ ✗]
└─▪ python run_analysis.py  configs/lanl/config.20170120.beta0.GMPAS-QU240.wolf  

Plotting streamfunction of Meridional Overturning Circulation (MOC)...

  List of files for climatologies:
    mpaso.hist.am.timeSeriesStatsMonthly.0001-01-01.nc through
    mpaso.hist.am.timeSeriesStatsMonthly.0002-12-01.nc

  List of files for time series:
    mpaso.hist.am.timeSeriesStatsMonthly.0001-01-01.nc through
    mpaso.hist.am.timeSeriesStatsMonthly.0002-12-01.nc
/turquoise/users/pwolfram/MPAS-Analysis/mpas_analysis/shared/climatology/climatology.py:706: UserWarning: climatology start and/or end year different from requested
requestd: 0001-0003
actual:   0001-0002
  warnings.warn(message)
   Computing and caching climatologies covering 1-year spans...
     0001
     0002
Segmentation fault (core dumped)
┌─[pwolfram][wf-fe1][~/MPAS-Analysis][08:24][±][ ✗]
└─▪ python run_analysis.py  configs/lanl/config.20170120.beta0.GMPAS-QU240.wolf  

Plotting streamfunction of Meridional Overturning Circulation (MOC)...

  List of files for climatologies:
    mpaso.hist.am.timeSeriesStatsMonthly.0001-01-01.nc through
    mpaso.hist.am.timeSeriesStatsMonthly.0002-12-01.nc

  List of files for time series:
    mpaso.hist.am.timeSeriesStatsMonthly.0001-01-01.nc through
    mpaso.hist.am.timeSeriesStatsMonthly.0002-12-01.nc
/turquoise/users/pwolfram/MPAS-Analysis/mpas_analysis/shared/climatology/climatology.py:706: UserWarning: climatology start and/or end year different from requested
requestd: 0001-0003
actual:   0001-0002

  warnings.warn(message)
   Computing and caching climatologies covering 1-year spans...
HDF5-DIAG: Error detected in HDF5 (1.8.17) thread 47523961982496:
  #000: H5F.c line 604 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1087 in H5F_open(): unable to read superblock
    major: File accessibilty
    minor: Read failed
  #002: H5Fsuper.c line 294 in H5F_super_read(): unable to load superblock
    major: Object cache
    minor: Unable to protect metadata
  #003: H5AC.c line 1262 in H5AC_protect(): H5C_protect() failed.
    major: Object cache
    minor: Unable to protect metadata
  #004: H5C.c line 3574 in H5C_protect(): can't load entry
    major: Object cache
    minor: Unable to load metadata into cache
  #005: H5C.c line 7954 in H5C_load_entry(): unable to load entry
    major: Object cache
    minor: Unable to load metadata into cache
  #006: H5Fsuper_cache.c line 476 in H5F_sblock_load(): truncated file: eof = 2654208, sblock->base_addr = 0, stored_eoa = 14252219
    major: File accessibilty
    minor: File has been truncated
Traceback (most recent call last):
  File "run_analysis.py", line 230, in <module>
    analysis(config)
  File "run_analysis.py", line 165, in analysis
    moc_streamfunction(config)
  File "/turquoise/users/pwolfram/MPAS-Analysis/mpas_analysis/ocean/meridional_overturning_circulation.py", line 152, in moc_streamfunction
    variableMap, calendar)
  File "/turquoise/users/pwolfram/MPAS-Analysis/mpas_analysis/ocean/meridional_overturning_circulation.py", line 271, in _cache_velocity_climatologies
    printProgress=True)
  File "/turquoise/users/pwolfram/MPAS-Analysis/mpas_analysis/shared/climatology/climatology.py", line 573, in cache_climatologies
    dsCached = xr.open_dataset(outputFileClimo)
  File "/net/scratch1/pwolfram/miniconda2/lib/python2.7/site-packages/xarray/backends/api.py", line 287, in open_dataset
    store = backends.NetCDF4DataStore(filename_or_obj, group=group)
  File "/net/scratch1/pwolfram/miniconda2/lib/python2.7/site-packages/xarray/backends/netCDF4_.py", line 205, in __init__
    self.ds = opener()
  File "/net/scratch1/pwolfram/miniconda2/lib/python2.7/site-packages/xarray/backends/netCDF4_.py", line 181, in _open_netcdf4_group
    ds = nc4.Dataset(filename, mode=mode, **kwargs)
  File "netCDF4/_netCDF4.pyx", line 1848, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:13992)
IOError: NetCDF: HDF error
```

**Comment by pwolfram** [comment]
This was observed in #169

**Comment by pwolfram** [comment]
>  Maybe you delete an existing cache file on any OSError when opening that file?

@xylar, this sounds reasonable to me-- are you ok with that strategy?

**Comment by pwolfram** [comment]
This should be covered by #180.  Please reopen if there are additional problems.
