### ISSUE TITLE
Problems installing on laptop - need specific conda version?

### ISSUE THREAD

**Issue by akturner** [MPAS-Dev/MPAS-Analysis#185]
Hi, I'm trying to install the tools on my laptop but when I run it I get the following issue:

pn1512828:MPAS-Analysis akt$ ./run_analysis.py config.setup
/Users/akt/anaconda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')

Plotting sea-ice area and volume time series...

Reading files:
timeSeriesStatsMonthly.1959-12.nc through
timeSeriesStatsMonthly.1962-01.nc
Load sea-ice data...
Warning: Preprocessed time series ends before the timeSeries startYear and will not be plotted.
Caching NH data
Process and save time series
1960-1961
Make NH plots...
Traceback (most recent call last):
File "./run_analysis.py", line 230, in 
analysis(config)
File "./run_analysis.py", line 173, in analysis
seaice_timeseries(config)
File "/Users/akt/Work/MPAS-CICE/MPAS-Analysis/feature_branches/standalone/development/MPAS-Analysis/mpas_analysis/sea_ice/timeseries.py", line 304, in seaice_timeseries
calendar=calendar)
File "/Users/akt/Work/MPAS-CICE/MPAS-Analysis/feature_branches/standalone/development/MPAS-Analysis/mpas_analysis/shared/plot/plotting.py", line 425, in timeseries_analysis_plot
mean = pd.Series.rolling(dsvalue.to_pandas(), N, center=True).mean()
AttributeError: type object 'Series' has no attribute 'rolling'

It seems I need a specific version of conda for this to work. Currently I have installed:

pn1512828:MPAS-Analysis akt$ conda info
Current conda install:

           platform : osx-64
      conda version : 4.3.16
   conda is private : False
  conda-env version : 4.3.16
conda-build version : 1.18.2
     python version : 2.7.12.final.0
   requests version : 2.13.0
   root environment : /Users/akt/anaconda  (writable)
default environment : /Users/akt/anaconda
   envs directories : /Users/akt/anaconda/envs
                      /Users/akt/.conda/envs
      package cache : /Users/akt/anaconda/pkgs
                      /Users/akt/.conda/pkgs
       channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                      https://repo.continuum.io/pkgs/free/noarch
                      https://repo.continuum.io/pkgs/r/osx-64
                      https://repo.continuum.io/pkgs/r/noarch
                      https://repo.continuum.io/pkgs/pro/osx-64
                      https://repo.continuum.io/pkgs/pro/noarch
        config file : None
       offline mode : False
         user-agent : conda/4.3.16 requests/2.13.0 CPython/2.7.12 Darwin/14.5.0 OSX/10.10.5
            UID:GID : 502:20
What is the recommended version?? Thanks!

**Comment by akturner** [comment]
@pwolfram: suggests this might be a issue with panda version. I like the version with the sneezing panda - he so cute!

**Comment by akturner** [comment]
Updating pandas seemed to fix this
