### ISSUE TITLE
MPAS-Analysis seems to assume namelists are lowercase

### ISSUE THREAD

**Issue by akturner** [MPAS-Dev/MPAS-Analysis#207]
I'm trying to use the MPAS_Analysis system on MPAS-Seaice standalone simulations. These fail with the following error:
Traceback (most recent call last):
  File "./run_analysis.py", line 202, in build_analysis_list
    analysisTask.setup_and_check()
  File "/Users/akt/Work/MPAS-Analysis/Feature_branches/init/MPAS-Analysis/mpas_analysis/sea_ice/climatology_map.py", line 76, in setup_and_check
    raiseException=True)
  File "/Users/akt/Work/MPAS-Analysis/Feature_branches/init/MPAS-Analysis/mpas_analysis/shared/analysis_task.py", line 291, in check_analysis_enabled
    'member.'.format(analysisOptionName))
RuntimeError: *** MPAS-Analysis relies on config_am_timeseriesstatsmonthly_enable = .true.
*** Make sure to enable this analysis member.
ERROR: analysis module climatologyMapSeaIceConcThick failed during check and will not be run

However, in the namelist file
config_AM_timeSeriesStatsMonthly_enable = true

Looking at the code it seems that the analysis system assumes that all namelists options are lowercase, which is not necessarily the case, although fortran is case insensitive. Maybe an easy fix is to convert all namelist options to lower case as the namelist object is constructed?

**Comment by akturner** [comment]
The following PR solves the issue:
https://github.com/MPAS-Dev/MPAS-Analysis/pull/208
