### ISSUE TITLE
MOC calculation does not work for 18to6

### ISSUE THREAD

**Issue by vanroekel** [MPAS-Dev/MPAS-Analysis#218]
I'm trying to use MPAS-Analysis v0.2 to analyze the 18to6 output on OLCF.  I've tried this on titan and rhea on login nodes and batch mode.  It does not work on either rhea or titan.  Here is the error I receive on rhea
```
Command: mpirun -n 1 --map-by ppr:1:node /lustre/atlas1/cli115/proj-shared/vanroek/a-prime/python/MPAS-Analysis/run_analysis.py --generate streamfunctionMOC /lustre/atlas1/cli115/proj-shared/vanroek/a-prime/python/MPAS-Analysis/config.default /lustre/atlas1/cli115/scratch/vanroek/plots/coupled_diagnostics_GMPAS-IAF_RRS18to6_years24-54_vs_obs.logs/config.ocnice.2017-07-20_104312
/lustre/atlas1/cli115/proj-shared/vanroek/a-prime/python/MPAS-Analysis/mpas_analysis/shared/climatology/climatology.py:821: UserWarning: Deleting cache file /lustre/atlas1/cli115/scratch/vanroek/plots/coupled_diagnostics_GMPAS-IAF_RRS18to6_years24-54_vs_obs.scratch/clim/mpas//meanVelocity_year0024.nc, which appears to have been corrupted.
  warnings.warn(message)

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 94124 RUNNING AT rhea2
=   EXIT CODE: 9
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Killed (signal 9)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions
```
Here is the error on titan
```
  List of files for time series:
    mpaso.hist.am.timeSeriesStatsMonthly.0039-12-01.nc through
    mpaso.hist.am.timeSeriesStatsMonthly.0043-01-01.nc
   Computing and caching climatologies covering 1-year spans...
     0040
Traceback (most recent call last):
  File "/lustre/atlas1/cli115/proj-shared/vanroek/a-prime/python/MPAS-Analysis/run_analysis.py", line 224, in run_analysis
    analysisTask.run()
  File "/lustre/atlas1/cli115/proj-shared/vanroek/a-prime/python/MPAS-Analysis/mpas_analysis/ocean/streamfunction_moc.py", line 166, in run
    self._cache_velocity_climatologies()
  File "/lustre/atlas1/cli115/proj-shared/vanroek/a-prime/python/MPAS-Analysis/mpas_analysis/ocean/streamfunction_moc.py", line 279, in _cache_velocity_climatologies
    printProgress=True)
  File "/lustre/atlas1/cli115/proj-shared/vanroek/a-prime/python/MPAS-Analysis/mpas_analysis/shared/climatology/climatology.py", line 491, in cache_climatologies
    calendar)
  File "/lustre/atlas1/cli115/proj-shared/vanroek/a-prime/python/MPAS-Analysis/mpas_analysis/shared/climatology/climatology.py", line 885, in _cache_individual_climatologies
    climatology.to_netcdf(outputFileClimo)
  File "/ccs/proj/cli115/pwolfram/anaconda_envs/default-2.7/lib/python2.7/site-packages/xarray/core/dataset.py", line 953, in to_netcdf
    unlimited_dims=unlimited_dims)
  File "/ccs/proj/cli115/pwolfram/anaconda_envs/default-2.7/lib/python2.7/site-packages/xarray/backends/api.py", line 584, in to_netcdf
    unlimited_dims=unlimited_dims)
  File "/ccs/proj/cli115/pwolfram/anaconda_envs/default-2.7/lib/python2.7/site-packages/xarray/core/dataset.py", line 895, in dump_to_store
    store.sync()
  File "/ccs/proj/cli115/pwolfram/anaconda_envs/default-2.7/lib/python2.7/site-packages/xarray/backends/netCDF4_.py", line 336, in sync
    super(NetCDF4DataStore, self).sync()
  File "/ccs/proj/cli115/pwolfram/anaconda_envs/default-2.7/lib/python2.7/site-packages/xarray/backends/common.py", line 202, in sync
    self.writer.sync()
  File "/ccs/proj/cli115/pwolfram/anaconda_envs/default-2.7/lib/python2.7/site-packages/xarray/backends/common.py", line 179, in sync
    da.store(self.sources, self.targets, lock=GLOBAL_LOCK)
  File "/ccs/proj/cli115/pwolfram/anaconda_envs/default-2.7/lib/python2.7/site-packages/dask/array/core.py", line 877, in store
    Array._get(dsk, keys, **kwargs)
  File "/ccs/proj/cli115/pwolfram/anaconda_envs/default-2.7/lib/python2.7/site-packages/dask/base.py", line 102, in _get
    return get(dsk2, keys, **kwargs)
  File "/ccs/proj/cli115/pwolfram/anaconda_envs/default-2.7/lib/python2.7/site-packages/dask/threaded.py", line 76, in get
    **kwargs)
  File "/ccs/proj/cli115/pwolfram/anaconda_envs/default-2.7/lib/python2.7/site-packages/dask/async.py", line 500, in get_async
    raise(remote_exception(res, tb))
MemoryError:

Traceback
---------
  File "/ccs/proj/cli115/pwolfram/anaconda_envs/default-2.7/lib/python2.7/site-packages/dask/async.py", line 266, in execute_task
    result = _execute_task(task, data)
  File "/ccs/proj/cli115/pwolfram/anaconda_envs/default-2.7/lib/python2.7/site-packages/dask/async.py", line 247, in _execute_task
    return func(*args2)

ERROR: analysis module streamfunctionMOC failed during run
Traceback (most recent call last):
  File "/lustre/atlas1/cli115/proj-shared/vanroek/a-prime/python/MPAS-Analysis/run_analysis.py", line 295, in <module>
    run_analysis(config, analyses)
  File "/lustre/atlas1/cli115/proj-shared/vanroek/a-prime/python/MPAS-Analysis/run_analysis.py", line 249, in run_analysis
    raise lastException
dask.async.MemoryError:

Traceback
---------
  File "/ccs/proj/cli115/pwolfram/anaconda_envs/default-2.7/lib/python2.7/site-packages/dask/async.py", line 266, in execute_task
    result = _execute_task(task, data)
  File "/ccs/proj/cli115/pwolfram/anaconda_envs/default-2.7/lib/python2.7/site-packages/dask/async.py", line 247, in _execute_task
    return func(*args2)
```

I have tried numerous values of maxChunkSize, but none remedy the problem.

Path to output from a-prime test 
```
/lustre/atlas1/cli115/scratch/vanroek/plots/coupled_diagnostics_GMPAS-IAF_RRS18to6_years40-42_vs_obs.logs
```
Path to simulation output
```
/lustre/atlas1/cli115/scratch/vanroek/GMPAS-IAF_RRS18to6/run
```

**Comment by xylar** [comment]
@pwolfram, this might be one for you?

**Comment by pwolfram** [comment]
Thanks @xylar for bringing this to my attention-- I'm looking into this issue with @vanroekel.

**Comment by milenaveneziani** [comment]
Hopefully this will be solved by #220.

**Comment by xylar** [comment]
@vanroekel, can we close this for now and open another issue if the new method of computing MOC still doesn't work?  Currently, issues I'm aware of are:
* bad transect for the southern boundary; should be fixed by https://github.com/MPAS-Dev/MPAS-Tools/pull/181
* CDF5 issues for big variables; solution in progress
Neither of these are issues with MPAS-Analysis directly.

**Comment by vanroekel** [comment]
Closing sounds fine to me.
