### ISSUE TITLE
Errors in streamfunctionMOC with latest dask (0.15.3)

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#254]
When I update my conda environment to the latest dask (0.15.3), I get the following error message when I run streamfunctionMOC:

```
ERROR: analysis task streamfunctionMOC failed during run
Traceback (most recent call last):
  File "/home/xylar/code/mpas-work/analysis/mpas_analysis_repo/run_mpas_analysis", line 340, in run_analysis
    analysisTask.run()
  File "/home/xylar/code/mpas-work/analysis/mpas_analysis_repo/mpas_analysis/ocean/streamfunction_moc.py", line 208, in run
    dsMOCTimeSeries = self._compute_moc_time_series_postprocess()
  File "/home/xylar/code/mpas-work/analysis/mpas_analysis_repo/mpas_analysis/ocean/streamfunction_moc.py", line 573, in _compute_moc_time_series_postprocess
    self.calendar, yearsPerCacheUpdate=1,  printProgress=False)
  File "/home/xylar/code/mpas-work/analysis/mpas_analysis_repo/mpas_analysis/shared/time_series/time_series.py", line 127, in cache_time_series
    ds = timeSeriesCalcFunction(timeIndices, firstProcessed)
  File "/home/xylar/code/mpas-work/analysis/mpas_analysis_repo/mpas_analysis/ocean/streamfunction_moc.py", line 593, in _compute_moc_time_series_part
    dsLocal = ds.isel(Time=timeIndex)
  File "/home/xylar/miniconda2/envs/mpas_analysis/lib/python2.7/site-packages/xarray/core/dataset.py", line 1143, in isel
    new_var = var.isel(**var_indexers)
  File "/home/xylar/miniconda2/envs/mpas_analysis/lib/python2.7/site-packages/xarray/core/variable.py", line 570, in isel
    return self[tuple(key)]
  File "/home/xylar/miniconda2/envs/mpas_analysis/lib/python2.7/site-packages/xarray/core/variable.py", line 400, in __getitem__
    values = self._indexable_data[key]
  File "/home/xylar/miniconda2/envs/mpas_analysis/lib/python2.7/site-packages/xarray/core/indexing.py", line 498, in __getitem__
    value = self.array[key]
  File "/home/xylar/miniconda2/envs/mpas_analysis/lib/python2.7/site-packages/dask/array/core.py", line 1222, in __getitem__
    index2 = normalize_index(index, self.shape)
  File "/home/xylar/miniconda2/envs/mpas_analysis/lib/python2.7/site-packages/dask/array/slicing.py", line 762, in normalize_index
    raise IndexError("Too many indices for array")
IndexError: Too many indices for array
```
The error is not present with the version of dask (015.2) in acme-unified.  This issue needs to be addressed somehow or other before we update the dask version in acme-unified.

**Comment by xylar** [comment]
This seems to possibly be relate to https://github.com/dask/dask/issues/2745

**Comment by xylar** [comment]
The solution seems to be to skip dask 0.15.3 and wait for the next release, which should include a fix.

**Comment by xylar** [comment]
I have run the MOC successfully with dask 0.15.4, so I will close this issue.
