### ISSUE TITLE
Current develop crashes on edison

### ISSUE THREAD

**Issue by milenaveneziani** [MPAS-Dev/MPAS-Analysis#360]
While running MPAS-Analysis on the DECK pi-control simulation on edison, I encountered this error message immediately:
```
Traceback (most recent call last):
  File "./run_mpas_analysis", line 555, in <module>
    analyses = build_analysis_list(config, refConfig)
  File "./run_mpas_analysis", line 87, in build_analysis_list
    config=config,  componentName='ocean')
  File "/global/u2/m/milena/MPAS-git-repositories/MPAS-Analysis/mpas_analysis/shared/climatology/ref_year_mpas_climatology_task.py", line 66, in __init__
    config.write(config_string)
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison_e3sm_unified_1.1.3_py2_nox/lib/python2.7/ConfigParser.py", line 407, in write
    fp.write("[%s]\n" % section)
TypeError: unicode argument expected, got 'str'
```

I then backed up a few commits, until this one:
`ae41246 Merge pull request #346 from xylar/update_default_iceshelves`
and still got the message. The one that works is the v0.7.5 tag.

**Comment by xylar** [comment]
Addressed by #361
