### ISSUE TITLE
Error in OHC maps for non year 1 start times

### ISSUE THREAD

**Issue by vanroekel** [MPAS-Dev/MPAS-Analysis#441]
When running the latest analysis on the historical transient, I see the following error for the OHCAnomaly maps
```
Traceback (most recent call last):
  File "./run_mpas_analysis", line 265, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/global/u2/l/lvroekel/MPAS-Analysis/mpas_analysis/shared/climatology/mpas_climatology_task.py", line 211, in setup_and_check
    self.endDate))
IOError: No files were found in stream timeSeriesStatsMonthlyOutput between 0001-01-01_00:00:00 and 0001-12-31_23:59:59.
ERROR: analysis task refYearMpasClimatologyOcean failed during check and will not be run
ERROR: prerequisite task refYearMpasClimatologyOcean of analysis task climatologyMapOHCAnomaly failed during check,
       so this task will not be run
```
It is not respecting the value of anomalyRefYear I set.  This appears to be a simple typo in the task.  I will make a PR in a minute

**Comment by xylar** [comment]
Addressed bu #442
