### ISSUE TITLE
Permission denied error while computing ocean climos

### ISSUE THREAD

**Issue by sterlingbaldwin** [MPAS-Dev/MPAS-Analysis#503]
I got the following error log while running MPAS-Analysis on a single year of output. Also attached is the run config. I was running v1.1 from the e3sm conda channel. 
```
mpasClimatologyOcean.log:

Computing MPAS climatologies from files:
    mpaso.hist.am.timeSeriesStatsMonthly.0105-01-01.nc through
    mpaso.hist.am.timeSeriesStatsMonthly.0105-12-01.nc
running: ncclimo -4 --clm_md=mth -a sdd -m mpaso -p bck -v timeMonthly_avg_dThreshMLD,timeMonthly_avg_activeTracers_temperature,timeMonthly_avg_activeTracers_salinity,timeMonthly_avg_pressureAdjustedSSH,timeMonthly_avg_velocityZonal,timeMonthly_avg_velocityMeridional,timeMonthly_avg_layerThickness,timeMonthly_avg_potentialDensity,timeMonthly_avg_meridionalHeatTransportLat,timeMonthly_avg_meridionalHeatTransportLatZ,timeMonthly_avg_normalVelocity,timeMonthly_avg_vertVelocityTop,timeMonthly_avg_normalGMBolusVelocity,timeMonthly_avg_vertGMBolusVelocityTop --seasons=JFM,JAS,ANN -s 0105 -e 0105 -i//p/user_pub/e3sm/baldwin32/deck/bcrc_spinup/mpas_output/0105-0105-obs/clim/mpas/source_symlinks -o //p/user_pub/e3sm/baldwin32/deck/bcrc_spinup/mpas_output/0105-0105-obs/clim/mpas/unmasked_oEC60to30v3
Climatology operations invoked with command:
/usr/local/e3sm_unified/envs/base/envs/e3sm_unified_1.2.3_py2.7_nox/bin/ncclimo -4 --clm_md=mth -a sdd -m mpaso -p bck -v timeMonthly_avg_dThreshMLD,timeMonthly_avg_activeTracers_temperature,timeMonthly_avg_activeTracers_salinity,timeMonthly_avg_pressureAdjustedSSH,timeMonthly_avg_velocityZonal,timeMonthly_avg_velocityMeridional,timeMonthly_avg_layerThickness,timeMonthly_avg_potentialDensity,timeMonthly_avg_meridionalHeatTransportLat,timeMonthly_avg_meridionalHeatTransportLatZ,timeMonthly_avg_normalVelocity,timeMonthly_avg_vertVelocityTop,timeMonthly_avg_normalGMBolusVelocity,timeMonthly_avg_vertGMBolusVelocityTop --seasons=JFM,JAS,ANN -s 0105 -e 0105 -i //p/user_pub/e3sm/baldwin32/deck/bcrc_spinup/mpas_output/0105-0105-obs/clim/mpas/source_symlinks -o //p/user_pub/e3sm/baldwin32/deck/bcrc_spinup/mpas_output/0105-0105-obs/clim/mpas/unmasked_oEC60to30v3
Started climatology splitting at Wed Dec  5 14:47:24 PST 2018
Running climatology script ncclimo from directory /usr/local/e3sm_unified/envs/base/envs/e3sm_unified_1.2.3_py2.7_nox/bin
NCO binaries version 4.7.7 from directory /usr/local/e3sm_unified/envs/base/envs/e3sm_unified_1.2.3_py2.7_nox/bin
Parallelism mode = Background
Producing standard climatology from raw input files in directory //p/user_pub/e3sm/baldwin32/deck/bcrc_spinup/mpas_output/0105-0105-obs/clim/mpas/source_symlinks
Output files to directory //p/user_pub/e3sm/baldwin32/deck/bcrc_spinup/mpas_output/0105-0105-obs/clim/mpas/unmasked_oEC60to30v3
Climatology from 1 years of contiguous raw data touching 1 calendar years from YYYYMM = 010501 to 010512
Input filenames will be constructed with CESM'ish or E3SM/ACME'ish conventions
Each input file assumed to contain mean of one month
Winter statistics based on seasonally discontiguous December (sdd-mode): DJF sequences comprise three months from the same calendar year
Annotation for CF climatology attribute and climatology_bounds variable will be performed
This climatology will not be regridded
Generating climatology...
Climatological monthly mean for month 1 ...
Climatological monthly mean for month 2 ...
Climatological monthly mean for month 3 ...
Climatological monthly mean for month 4 ...
Climatological monthly mean for month 5 ...
Climatological monthly mean for month 6 ...
Climatological monthly mean for month 7 ...
Climatological monthly mean for month 8 ...
Climatological monthly mean for month 9 ...
Climatological monthly mean for month 10 ...
Climatological monthly mean for month 11 ...
Climatological monthly mean for month 12 ...
ERROR: nco__create() unable to create file "//p/user_pub/e3sm/baldwin32/deck/bcrc_spinup/mpas_output/0105-0105-obs/clim/mpas/unmasked_oEC60to30v3/mpaso_03_010503_010503_climo.nc"
nco_err_exit(): ERROR NCO will now exit with system call exit(EXIT_FAILURE)
ERROR: nco__create() unable to create file "//p/user_pub/e3sm/baldwin32/deck/bcrc_spinup/mpas_output/0105-0105-obs/clim/mpas/unmasked_oEC60to30v3/mpaso_06_010506_010506_climo.nc"
nco_err_exit(): ERROR NCO will now exit with system call exit(EXIT_FAILURE)
ERROR: nco__create() unable to create file "//p/user_pub/e3sm/baldwin32/deck/bcrc_spinup/mpas_output/0105-0105-obs/clim/mpas/unmasked_oEC60to30v3/mpaso_09_010509_010509_climo.nc"
nco_err_exit(): ERROR NCO will now exit with system call exit(EXIT_FAILURE)
ERROR: nco__create() unable to create file "//p/user_pub/e3sm/baldwin32/deck/bcrc_spinup/mpas_output/0105-0105-obs/clim/mpas/unmasked_oEC60to30v3/mpaso_05_010505_010505_climo.nc"
nco_err_exit(): ERROR NCO will now exit with system call exit(EXIT_FAILURE)
ERROR: nco__create() unable to create file "//p/user_pub/e3sm/baldwin32/deck/bcrc_spinup/mpas_output/0105-0105-obs/clim/mpas/unmasked_oEC60to30v3/mpaso_07_010507_010507_climo.nc"
nco_err_exit(): ERROR NCO will now exit with system call exit(EXIT_FAILURE)
ERROR: nco__create() unable to create file "//p/user_pub/e3sm/baldwin32/deck/bcrc_spinup/mpas_output/0105-0105-obs/clim/mpas/unmasked_oEC60to30v3/mpaso_11_010511_010511_climo.nc"
nco_err_exit(): ERROR NCO will now exit with system call exit(EXIT_FAILURE)
ERROR: nco__create() unable to create file "//p/user_pub/e3sm/baldwin32/deck/bcrc_spinup/mpas_output/0105-0105-obs/clim/mpas/unmasked_oEC60to30v3/mpaso_02_010502_010502_climo.nc"
nco_err_exit(): ERROR NCO will now exit with system call exit(EXIT_FAILURE)
ERROR: nco__create() unable to create file "//p/user_pub/e3sm/baldwin32/deck/bcrc_spinup/mpas_output/0105-0105-obs/clim/mpas/unmasked_oEC60to30v3/mpaso_01_010501_010501_climo.nc"
nco_err_exit(): ERROR NCO will now exit with system call exit(EXIT_FAILURE)
ERROR: nco__create() unable to create file "//p/user_pub/e3sm/baldwin32/deck/bcrc_spinup/mpas_output/0105-0105-obs/clim/mpas/unmasked_oEC60to30v3/mpaso_08_010508_010508_climo.nc"
nco_err_exit(): ERROR NCO will now exit with system call exit(EXIT_FAILURE)
ERROR: nco__create() unable to create file "//p/user_pub/e3sm/baldwin32/deck/bcrc_spinup/mpas_output/0105-0105-obs/clim/mpas/unmasked_oEC60to30v3/mpaso_10_010510_010510_climo.nc"
nco_err_exit(): ERROR NCO will now exit with system call exit(EXIT_FAILURE)
ncclimo: ERROR monthly climo cmd_clm[1] failed. Debug this:
 ncra --cb -O --no_tmp_fl --fl_fmt=netcdf4 -v timeMonthly_avg_dThreshMLD,timeMonthly_avg_activeTracers_temperature,timeMonthly_avg_activeTracers_salinity,timeMonthly_avg_pressureAdjustedSSH,timeMonthly_avg_velocityZonal,timeMonthly_avg_velocityMeridional,timeMonthly_avg_layerThickness,timeMonthly_avg_potentialDensity,timeMonthly_avg_meridionalHeatTransportLat,timeMonthly_avg_meridionalHeatTransportLatZ,timeMonthly_avg_normalVelocity,timeMonthly_avg_vertVelocityTop,timeMonthly_avg_normalGMBolusVelocity,timeMonthly_avg_vertGMBolusVelocityTop --dfl_lvl=0 --hdr_pad=10000 --gaa climo_script=ncclimo --gaa climo_command="'/usr/local/e3sm_unified/envs/base/envs/e3sm_unified_1.2.3_py2.7_nox/bin/ncclimo -4 --clm_md=mth -a sdd -m mpaso -p bck -v timeMonthly_avg_dThreshMLD,timeMonthly_avg_activeTracers_temperature,timeMonthly_avg_activeTracers_salinity,timeMonthly_avg_pressureAdjustedSSH,timeMonthly_avg_velocityZonal,timeMonthly_avg_velocityMeridional,timeMonthly_avg_layerThickness,timeMonthly_avg_potentialDensity,timeMonthly_avg_meridionalHeatTransportLat,timeMonthly_avg_meridionalHeatTransportLatZ,timeMonthly_avg_normalVelocity,timeMonthly_avg_vertVelocityTop,timeMonthly_avg_normalGMBolusVelocity,timeMonthly_avg_vertGMBolusVelocityTop --seasons=JFM,JAS,ANN -s 0105 -e 0105 -i //p/user_pub/e3sm/baldwin32/deck/bcrc_spinup/mpas_output/0105-0105-obs/clim/mpas/source_symlinks -o //p/user_pub/e3sm/baldwin32/deck/bcrc_spinup/mpas_output/0105-0105-obs/clim/mpas/unmasked_oEC60to30v3'" --gaa climo_hostname=acme1 --gaa climo_version=4.7.7 --gaa yrs_averaged=0105 -p //p/user_pub/e3sm/baldwin32/deck/bcrc_spinup/mpas_output/0105-0105-obs/clim/mpas/source_symlinks  mpaso.hist.am.timeSeriesStatsMonthly.0105-01-01.nc //p/user_pub/e3sm/baldwin32/deck/bcrc_spinup/mpas_output/0105-0105-obs/clim/mpas/unmasked_oEC60to30v3/mpaso_01_010501_010501_climo.nc
ERROR: nco__create() unable to create file "//p/user_pub/e3sm/baldwin32/deck/bcrc_spinup/mpas_output/0105-0105-obs/clim/mpas/unmasked_oEC60to30v3/mpaso_12_010512_010512_climo.nc"
nco_err_exit(): ERROR NCO will now exit with system call exit(EXIT_FAILURE)

HDF5-DIAG: Error detected in HDF5 (1.10.2) thread 140532454893440:
  #000: H5F.c line 445 in H5Fcreate(): unable to create file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1519 in H5F_open(): unable to lock the file
    major: File accessibilty
    minor: Unable to open file
  #002: H5FD.c line 1650 in H5FD_lock(): driver lock request failed
    major: Virtual File Layer
    minor: Can't update object
  #003: H5FDsec2.c line 941 in H5FD_sec2_lock(): unable to lock file, errno = 11, error message = 'Resource temporarily unavailable'
    major: File accessibilty
    minor: Bad file ID accessed
nco_err_exit(): ERROR Short NCO-generated message (usually name of function that triggered error): nco__create()
nco_err_exit(): ERROR Error code is 13. Translation into English with nc_strerror(13) is "Permission denied"
HDF5-DIAG: Error detected in HDF5 (1.10.2) thread 140586738833280:
  #000: H5F.c line 445 in H5Fcreate(): unable to create file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1519 in H5F_open(): unable to lock the file
    major: File accessibilty
    minor: Unable to open file
  #002: H5FD.c line 1650 in H5FD_lock(): driver lock request failed
    major: Virtual File Layer
    minor: Can't update object
  #003: H5FDsec2.c line 941 in H5FD_sec2_lock(): unable to lock file, errno = 11, error message = 'Resource temporarily unavailable'
    major: File accessibilty
    minor: Bad file ID accessed
nco_err_exit(): ERROR Short NCO-generated message (usually name of function that triggered error): nco__create()
nco_err_exit(): ERROR Error code is 13. Translation into English with nc_strerror(13) is "Permission denied"
HDF5-DIAG: Error detected in HDF5 (1.10.2) thread 139992600049536:
  #000: H5F.c line 445 in H5Fcreate(): unable to create file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1519 in H5F_open(): unable to lock the file
    major: File accessibilty
    minor: Unable to open file
  #002: H5FD.c line 1650 in H5FD_lock(): driver lock request failed
    major: Virtual File Layer
    minor: Can't update object
  #003: H5FDsec2.c line 941 in H5FD_sec2_lock(): unable to lock file, errno = 11, error message = 'Resource temporarily unavailable'
    major: File accessibilty
    minor: Bad file ID accessed
nco_err_exit(): ERROR Short NCO-generated message (usually name of function that triggered error): nco__create()
nco_err_exit(): ERROR Error code is 13. Translation into English with nc_strerror(13) is "Permission denied"
HDF5-DIAG: Error detected in HDF5 (1.10.2) thread 139638183790464:
  #000: H5F.c line 445 in H5Fcreate(): unable to create file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1519 in H5F_open(): unable to lock the file
    major: File accessibilty
    minor: Unable to open file
  #002: H5FD.c line 1650 in H5FD_lock(): driver lock request failed
    major: Virtual File Layer
    minor: Can't update object
  #003: H5FDsec2.c line 941 in H5FD_sec2_lock(): unable to lock file, errno = 11, error message = 'Resource temporarily unavailable'
    major: File accessibilty
    minor: Bad file ID accessed
HDF5-DIAG: Error detected in HDF5 (1.10.2) thread 140670758098816:
  #000: H5F.c line 445 in H5Fcreate(): unable to create file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1519 in H5F_open(): unable to lock the file
    major: File accessibilty
    minor: Unable to open file
  #002: H5FD.c line 1650 in H5FD_lock(): driver lock request failed
    major: Virtual File Layer
    minor: Can't update object
  #003: H5FDsec2.c line 941 in H5FD_sec2_lock(): unable to lock file, errno = 11, error message = 'Resource temporarily unavailable'
    major: File accessibilty
    minor: Bad file ID accessed
nco_err_exit(): ERROR Short NCO-generated message (usually name of function that triggered error): nco__create()
nco_err_exit(): ERROR Error code is 13. Translation into English with nc_strerror(13) is "Permission denied"
nco_err_exit(): ERROR Short NCO-generated message (usually name of function that triggered error): nco__create()
nco_err_exit(): ERROR Error code is 13. Translation into English with nc_strerror(13) is "Permission denied"
HDF5-DIAG: Error detected in HDF5 (1.10.2) thread 140226925782912:
  #000: H5F.c line 445 in H5Fcreate(): unable to create file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1519 in H5F_open(): unable to lock the file
    major: File accessibilty
    minor: Unable to open file
  #002: H5FD.c line 1650 in H5FD_lock(): driver lock request failed
    major: Virtual File Layer
    minor: Can't update object
  #003: H5FDsec2.c line 941 in H5FD_sec2_lock(): unable to lock file, errno = 11, error message = 'Resource temporarily unavailable'
    major: File accessibilty
    minor: Bad file ID accessed
nco_err_exit(): ERROR Short NCO-generated message (usually name of function that triggered error): nco__create()
nco_err_exit(): ERROR Error code is 13. Translation into English with nc_strerror(13) is "Permission denied"
HDF5-DIAG: Error detected in HDF5 (1.10.2) thread 140027436115840:
  #000: H5F.c line 445 in H5Fcreate(): unable to create file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1519 in H5F_open(): unable to lock the file
    major: File accessibilty
    minor: Unable to open file
  #002: H5FD.c line 1650 in H5FD_lock(): driver lock request failed
    major: Virtual File Layer
    minor: Can't update object
  #003: H5FDsec2.c line 941 in H5FD_sec2_lock(): unable to lock file, errno = 11, error message = 'Resource temporarily unavailable'
    major: File accessibilty
    minor: Bad file ID accessed
HDF5-DIAG: Error detected in HDF5 (1.10.2) thread 140325237540736:
  #000: H5F.c line 445 in H5Fcreate(): unable to create file
    major: File accessibilty
nco_err_exit(): ERROR Short NCO-generated message (usually name of function that triggered error): nco__create()
    minor: Unable to open file
nco_err_exit(): ERROR Error code is 13.   #001: H5Fint.c line 1519 in H5F_open(): unable to lock the file
    major: File accessibilty
Translation into English with nc_strerror(13) is "Permission denied"
    minor: Unable to open file
  #002: H5FD.c line 1650 in H5FD_lock(): driver lock request failed
    major: Virtual File Layer
    minor: Can't update object
  #003: H5FDsec2.c line 941 in H5FD_sec2_lock(): unable to lock file, errno = 11, error message = 'Resource temporarily unavailable'
    major: File accessibilty
    minor: Bad file ID accessed
nco_err_exit(): ERROR Short NCO-generated message (usually name of function that triggered error): nco__create()
nco_err_exit(): ERROR Error code is 13. Translation into English with nc_strerror(13) is "Permission denied"
HDF5-DIAG: Error detected in HDF5 (1.10.2) thread 140003651405696:
  #000: H5F.c line 445 in H5Fcreate(): unable to create file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1519 in H5F_open(): unable to lock the file
    major: File accessibilty
    minor: Unable to open file
  #002: H5FD.c line 1650 in H5FD_lock(): driver lock request failed
    major: Virtual File Layer
    minor: Can't update object
  #003: H5FDsec2.c line 941 in H5FD_sec2_lock(): unable to lock file, errno = 11, error message = 'Resource temporarily unavailable'
    major: File accessibilty
    minor: Bad file ID accessed
nco_err_exit(): ERROR Short NCO-generated message (usually name of function that triggered error): nco__create()
nco_err_exit(): ERROR Error code is 13. Translation into English with nc_strerror(13) is "Permission denied"
HDF5-DIAG: Error detected in HDF5 (1.10.2) thread 139859450554240:
  #000: H5F.c line 445 in H5Fcreate(): unable to create file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1519 in H5F_open(): unable to lock the file
    major: File accessibilty
    minor: Unable to open file
  #002: H5FD.c line 1650 in H5FD_lock(): driver lock request failed
    major: Virtual File Layer
    minor: Can't update object
  #003: H5FDsec2.c line 941 in H5FD_sec2_lock(): unable to lock file, errno = 11, error message = 'Resource temporarily unavailable'
    major: File accessibilty
    minor: Bad file ID accessed
nco_err_exit(): ERROR Short NCO-generated message (usually name of function that triggered error): nco__create()
nco_err_exit(): ERROR Error code is 13. Translation into English with nc_strerror(13) is "Permission denied"
HDF5-DIAG: Error detected in HDF5 (1.10.2) thread 140640233879424:
  #000: H5F.c line 445 in H5Fcreate(): unable to create file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1519 in H5F_open(): unable to lock the file
    major: File accessibilty
    minor: Unable to open file
  #002: H5FD.c line 1650 in H5FD_lock(): driver lock request failed
    major: Virtual File Layer
    minor: Can't update object
  #003: H5FDsec2.c line 941 in H5FD_sec2_lock(): unable to lock file, errno = 11, error message = 'Resource temporarily unavailable'
    major: File accessibilty
    minor: Bad file ID accessed
nco_err_exit(): ERROR Short NCO-generated message (usually name of function that triggered error): nco__create()
nco_err_exit(): ERROR Error code is 13. Translation into English with nc_strerror(13) is "Permission denied"

analysis task mpasClimatologyOcean failed during run
Traceback (most recent call last):
  File "/export/baldwin32/anaconda2/envs/flow/lib/python2.7/site-packages/mpas_analysis/shared/analysis_task.py", line 320, in run
    self.run_task()
  File "/export/baldwin32/anaconda2/envs/flow/lib/python2.7/site-packages/mpas_analysis/shared/climatology/mpas_climatology_task.py", line 265, in run_task
    outDirectory=climatologyDirectory)
  File "/export/baldwin32/anaconda2/envs/flow/lib/python2.7/site-packages/mpas_analysis/shared/climatology/mpas_climatology_task.py", line 450, in _compute_climatologies_with_ncclimo
    ' '.join(args))
CalledProcessError: Command 'ncclimo -4 --clm_md=mth -a sdd -m mpaso -p bck -v timeMonthly_avg_dThreshMLD,timeMonthly_avg_activeTracers_temperature,timeMonthly_avg_activeTracers_salinity,timeMonthly_avg_pressureAdjustedSSH,timeMonthly_avg_velocityZonal,timeMonthly_avg_velocityMeridional,timeMonthly_avg_layerThickness,timeMonthly_avg_potentialDensity,timeMonthly_avg_meridionalHeatTransportLat,timeMonthly_avg_meridionalHeatTransportLatZ,timeMonthly_avg_normalVelocity,timeMonthly_avg_vertVelocityTop,timeMonthly_avg_normalGMBolusVelocity,timeMonthly_avg_vertGMBolusVelocityTop --seasons=JFM,JAS,ANN -s 0105 -e 0105 -i //p/user_pub/e3sm/baldwin32/deck/bcrc_spinup/mpas_output/0105-0105-obs/clim/mpas/source_symlinks -o //p/user_pub/e3sm/baldwin32/deck/bcrc_spinup/mpas_output/0105-0105-obs/clim/mpas/unmasked_oEC60to30v3' returned non-zero exit status 1
```

mpas.cfg:
```
[runs]
mainRunName = 20181015_BCRC_1850SPINUP_OIBGC.ne30_oECv3.edison

[execute]
parallelTaskCount = 8
ncclimoParallelMode = bck

[input]
baseDirectory = /p/user_pub/e3sm/baldwin32/deck/bcrc_spinup/output/temp/bcrc_spinup/mpas_analysis/0105_0105_vs_obs
runSubdirectory = /p/user_pub/e3sm/baldwin32/deck/bcrc_spinup/output/temp/bcrc_spinup/mpas_analysis/0105_0105_vs_obs
oceanHistorySubdirectory = /p/user_pub/e3sm/baldwin32/deck/bcrc_spinup/output/temp/bcrc_spinup/mpas_analysis/0105_0105_vs_obs
seaIceHistorySubdirectory = /p/user_pub/e3sm/baldwin32/deck/bcrc_spinup/output/temp/bcrc_spinup/mpas_analysis/0105_0105_vs_obs
mpasMeshName = oEC60to30v3
mappingDirectory = /space2/diagnostics/mpas_analysis/maps

oceanNamelistFileName = mpaso_in
oceanStreamsFileName = streams.ocean
seaIceNamelistFileName = mpassi_in
seaIceStreamsFileName = streams.seaice

[output]
baseDirectory = /p/user_pub/e3sm/baldwin32/deck/bcrc_spinup/output/diags/bcrc_spinup/mpas_analysis/0105_0105_vs_obs
htmlSubdirectory = /var/www/acme/acme-diags/baldwin32/bcrc_spinup/mpas_analysis/0105_0105_vs_obs
generate = ["all_publicObs"]

[climatology]
startYear = 105
endYear = 105

[timeSeries]
startYear = 105
endYear = 105

[index]
startYear = 105
endYear = 105

[oceanObservations]
baseDirectory = /space2/diagnostics/observations/Ocean/

[seaIceObservations]
baseDirectory = /space2/diagnostics/observations/SeaIce/

[regions]
regionMaskDirectory = /space2/diagnostics/mpas_analysis/region_masks

[streamfunctionMOC]
usePostprocessingScript = True[runs]
mainRunName = 20181015_BCRC_1850SPINUP_OIBGC.ne30_oECv3.edison

[execute]
parallelTaskCount = 8
ncclimoParallelMode = bck

[input]
baseDirectory = /p/user_pub/e3sm/baldwin32/deck/bcrc_spinup/output/temp/bcrc_spinup/mpas_analysis/0105_0105_vs_obs
runSubdirectory = /p/user_pub/e3sm/baldwin32/deck/bcrc_spinup/output/temp/bcrc_spinup/mpas_analysis/0105_0105_vs_obs
oceanHistorySubdirectory = /p/user_pub/e3sm/baldwin32/deck/bcrc_spinup/output/temp/bcrc_spinup/mpas_analysis/0105_0105_vs_obs
seaIceHistorySubdirectory = /p/user_pub/e3sm/baldwin32/deck/bcrc_spinup/output/temp/bcrc_spinup/mpas_analysis/0105_0105_vs_obs
mpasMeshName = oEC60to30v3
mappingDirectory = /space2/diagnostics/mpas_analysis/maps

oceanNamelistFileName = mpaso_in
oceanStreamsFileName = streams.ocean
seaIceNamelistFileName = mpassi_in
seaIceStreamsFileName = streams.seaice

[output]
baseDirectory = //p/user_pub/e3sm/baldwin32/deck/bcrc_spinup/mpas_output/0105-0105-obs
htmlSubdirectory = /var/www/acme/acme-diags/baldwin32/bcrc_spinup/mpas_analysis/0105_0105_vs_obs
generate = ["all_publicObs"]

[climatology]
startYear = 105
endYear = 105

[timeSeries]
startYear = 105
endYear = 105

[index]
startYear = 105
endYear = 105

[oceanObservations]
baseDirectory = /space2/diagnostics/observations/Ocean/

[seaIceObservations]
baseDirectory = /space2/diagnostics/observations/SeaIce/

[regions]
regionMaskDirectory = /space2/diagnostics/mpas_analysis/region_masks

[streamfunctionMOC]
usePostprocessingScript = True
```

**Comment by sterlingbaldwin** [comment]
Update: I wiped everything and tried again. This time I got way more errors. Then I wiped eerything and tried again, and got NO errors at all. I suspect this to be a non-deterministic HDF5 issue.

**Comment by xylar** [comment]
I agree that this is likely an HDF5 issue and not (directly) and MPAS-Analysis issue.  Maybe try:
```bash
export HDF5_USE_FILE_LOCKING=FALSE
```
See #407 for discussion that *might* be related.

**Comment by sterlingbaldwin** [comment]
Ah, I remembered there was a flag but couldnt find it, thanks. I'll give it another try.

**Comment by xylar** [comment]
@sterlingbaldwin, has this issue recurred since using the export command above?  If not, can we close?

**Comment by sterlingbaldwin** [comment]
Ive been doing other stuff, so dont have any more recent findings to report. I'll setup a couple test runs to go today and let you know how it goes. If this isnt affecting anyone else, it might be a machine specific issue.

**Comment by xylar** [comment]
No one else has reported this specific issue and it does seem suspiciously like a machine-specific problem.  But I'm happy to keep the issue open until you have a chance to test further.  I mainly wanted to make sure it hadn't been definitively resolved by the HDF5 flag.
