### ISSUE TITLE
Error on last commit (remove autoclose)

### ISSUE THREAD

**Issue by milenaveneziani** [MPAS-Dev/MPAS-Analysis#505]
I just ran MPAS-Analysis using the latest develop and latest e3sm-unified (e3sm_unified_1.2.4_py2.7_nox) on edison, and I get the following error:
```
Traceback (most recent call last):
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/base/envs/e3sm_unified_1.2.4_py2.7_nox/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/base/envs/e3sm_unified_1.2.4_py2.7_nox/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/global/u2/m/milena/MPAS-git-repositories/MPAS-Analysis/mpas_analysis/__main__.py", line 794, in <module>
    main()
  File "/global/u2/m/milena/MPAS-git-repositories/MPAS-Analysis/mpas_analysis/__main__.py", line 752, in main
    'file_cache_maxsize'))
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/base/envs/e3sm_unified_1.2.4_py2.7_nox/lib/python2.7/site-packages/xarray/core/options.py", line 44, in __init__
    'options %r' % (invalid_options, set(OPTIONS)))
ValueError: argument names set(['file_cache_maxsize']) are not in the set of valid options set(['arithmetic_join', 'display_width', 'enable_cftimeindex'])
```

I went back to the previous commit (#5c25dfd) and didn't have this problem.

**Comment by xylar** [comment]
@milenaveneziani, sorry about this.  I'm going to test my fix (#506) on cori right now.
