### ISSUE TITLE
analysis task climatologyMapSSH_remapObservations failed during run

### ISSUE THREAD

**Issue by chengdang** [MPAS-Dev/MPAS-Analysis#525]
Hi:

I'm trying to run MPAS-analysis on NERSC edison, while it is terminated due to an error in task climatologyMapSSH.

Here is the terminal output for mpas_analysis:
```
python -m mpas_analysis ../scripts/m2o.SNICAR_AD_seaice.piControl.ne30_oEC.edison
running: ESMF_RegridWeightGen --source /tmp/lsf6d2fk.nc --destination /tmp/hky1qs6j.nc --weight /global/cscratch1/sd/cdang/acme_scratch/edison/archive/exp.SnicarTrue.cmip6-picontrol.nodeL/mpas_analysis/mapping/map_oEC60to30v3_to_WOCE_transects_5km_bilinear.nc --method bilinear --netcdf4 --no_log --src_regional --dst_regional --ignore_unmapped
Preprocessing SOSE transect data...
  temperature
  salinity
  potentialDensity
  zonalVelocity
  meridionalVelocity
  Done.
running: ESMF_RegridWeightGen --source /tmp/dvvghq2j.nc --destination /tmp/4l_2zhlc.nc --weight /global/cscratch1/sd/cdang/acme_scratch/edison/archive/exp.SnicarTrue.cmip6-picontrol.nodeL/mpas_analysis/mapping/map_oEC60to30v3_to_SOSE_transects_5km_bilinear.nc --method bilinear --netcdf4 --no_log --src_regional --dst_regional --ignore_unmapped
Running tasks:   1% |#                                                                                                                                   | ETA:   0:03:11ERROR in task climatologyMapSSH: remapObservations.  See log file /global/cscratch1/sd/cdang/acme_scratch/edison/archive/exp.SnicarTrue.cmip6-picontrol.nodeL/mpas_analysis/logs/climatologyMapSSH_remapObservations.log for details
Running tasks:  12% |###############                                                                     Running tasks:  76% |##################################Running tasks: 100% |##########################################################################################################################| Time:  0:34:53
```

Here is climatologyMapSSH_remapObservations.log:
```
analysis task climatologyMapSSH_remapObservations failed during run
Traceback (most recent call last):
  File "/global/u2/c/cdang/mpas_analysis/MPAS-Analysis/mpas_analysis/shared/analysis_task.py", line 320, in run
    self.run_task()
  File "/global/u2/c/cdang/mpas_analysis/MPAS-Analysis/mpas_analysis/shared/climatology/remap_observed_climatology_subtask.py", line 172, in run_task
    ds, monthValues, maskVaries=True)
  File "/global/u2/c/cdang/mpas_analysis/MPAS-Analysis/mpas_analysis/shared/climatology/climatology.py", line 212, in compute_climatology
    climatology = _compute_masked_mean(climatologyMonths, maskVaries)
  File "/global/u2/c/cdang/mpas_analysis/MPAS-Analysis/mpas_analysis/shared/climatology/climatology.py", line 599, in _compute_masked_mean
    dsWeightedSum = (ds * ds.daysInMonth).sum(dim='Time', keep_attrs=True)
  File "/global/homes/c/cdang/.conda/envs/mpas_analysis/lib/python3.7/site-packages/xarray/core/dataset.py", line 3326, in func
    ds = self._calculate_binary_op(g, other, join=align_type)
  File "/global/homes/c/cdang/.conda/envs/mpas_analysis/lib/python3.7/site-packages/xarray/core/dataset.py", line 3388, in _calculate_binary_op
    for k in self.data_vars)
  File "/global/homes/c/cdang/.conda/envs/mpas_analysis/lib/python3.7/site-packages/xarray/core/dataset.py", line 3388, in <genexpr>
    for k in self.data_vars)
  File "/global/homes/c/cdang/.conda/envs/mpas_analysis/lib/python3.7/site-packages/xarray/core/variable.py", line 1674, in func
    if not reflexive
TypeError: ufunc multiply cannot use operands with types dtype('<M8[ns]') and dtype('float64')

Execution time: 0:00:00.68
```

Any suggestions on how to solve this? Thank you!

**Comment by xylar** [comment]
@chengdang, could you also post the contents of your config file here?  I'd like to try to reproduce your MPAS-Analysis run.  I've never seen this error before.

**Comment by xylar** [comment]
Could you also post the results of:
```
conda activate mpas_analysis
conda list
```
That might tell me whether there's an issue with a package version.

**Comment by xylar** [comment]
Thanks for posting this, by the way.  I'm trying to build a new conda environment on my laptop right now to see if it might be an xarray issue or something like that.

**Comment by chengdang** [comment]
Sure! Here is the config file. Please let me know if you would also like access to the data.


```
[runs]
## options related to the run to be analyzed and control runs to be
## compared against

# mainRunName is a name that identifies the simulation being analyzed.
mainRunName = exp.SnicarTrue.cmip6-picontrol.nodeL

# config file for a control run to which this run will be compared.  The
# analysis should have already been run to completion once with this config
# file, so that the relevant MPAS climatologies already exist and have been
# remapped to the comparison grid.  Leave this option commented out if no
# control run is desired.
# controlRunConfigFile = /path/to/config/file

# config file for a main run on which the analysis was already run to
# completion.  The relevant MPAS climatologies already exist and have been
# remapped to the comparison grid and time series have been extracted.
# Leave this option commented out if the analysis for the main run should be
# performed.
# mainRunConfigFile = /path/to/config/file

[execute]
## options related to executing parallel tasks

# the number of parallel tasks (1 means tasks run in serial, the default)
parallelTaskCount = 4
 
# the parallelism mode in ncclimo ("serial" or "bck")
# Set this to "bck" (background parallelism) if running on a machine that can
# handle 12 simultaneous processes, one for each monthly climatology.
ncclimoParallelMode = bck

[diagnostics]
## config options related to observations, mapping files and region files used
## by MPAS-Analysis in diagnostics computations.

# The base path to the diagnostics directory.  Typically, this will be a shared
# directory on each E3SM supported machine (see the example config files for
# its location).  For other machines, this would be the directory pointed to
# when running "download_analysis_data.py" to get the public observations,
# mapping files and region files.
baseDirectory = /global/project/projectdirs/acme/diagnostics

[input]
## options related to reading in the results to be analyzed

# directory containing model results
baseDirectory = /global/cscratch1/sd/cdang/acme_scratch/edison/archive/exp.SnicarTrue.cmip6-picontrol.nodeL/

# subdirectory containing restart files
runSubdirectory = run
# subdirectory for ocean history files
oceanHistorySubdirectory = ocn/hist
# subdirectory for sea ice history files
seaIceHistorySubdirectory = ice/hist

# names of ocean and sea ice meshes (e.g. oEC60to30v3, oQU240v3, oRRS30to10v3, etc.)
mpasMeshName = oEC60to30v3

# names of namelist and streams files, either a path relative to baseDirectory
# or an absolute path.
oceanNamelistFileName = run/mpaso_in
oceanStreamsFileName = run/streams.ocean
seaIceNamelistFileName = run/mpassi_in
seaIceStreamsFileName = run/streams.seaice

[output]
## options related to writing out plots, intermediate cached data sets, logs,
## etc.

# directory where analysis should be written
baseDirectory = /global/cscratch1/sd/cdang/acme_scratch/edison/archive/exp.SnicarTrue.cmip6-picontrol.nodeL/mpas_analysis

# provide an absolute path to put HTML in an alternative location (e.g. a web
# portal)
# htmlSubdirectory = global/project/projectdirs/acme/www/USERNAME/RUNNAME
htmlSubdirectory = /global/project/projectdirs/m2833/www/cdang/mpas_analysis.m2o.SNICAR_AD_seaice.piControl.ne30_oEC.edison

# a list of analyses to generate.  Valid names can be seen by running:
#   mpas_analysis --list
# This command also lists tags for each analysis.
# Shortcuts exist to generate (or not generate) several types of analysis.
# These include:
#   'all' -- all analyses will be run
#   'all_<tag>' -- all analysis with a particular tag will be run
#   'all_<component>' -- all analyses from a given component (either 'ocean'
#                        or 'seaIce') will be run
#   'only_<component>', 'only_<tag>' -- all analysis from this component or
#                                       with this tag will be run, and all
#                                       analysis for other components or
#                                       without the tag will be skipped
#   'no_<task_name>' -- skip the given task
#   'no_<component>', 'no_<tag>' -- in analogy to 'all_*', skip all analysis
#                                   tasks from the given compoonent or with
#                                   the given tag.  Do
#                                      mpas_analysis --list
#                                   to list all task names and their tags
# an equivalent syntax can be used on the command line to override this
# option:
#    mpas_analysis config.analysis --generate \
#         all,no_ocean,all_timeSeries
# All tasks with tag "landIceCavities" are disabled because this run did not
# include land-ice cavities.
generate = ['all', 'no_landIceCavities', 'no_eke', 'no_BGC', 'no_icebergs']

[climatology]
## options related to producing climatologies, typically to compare against
## observations and previous runs

# the first year over which to average climatalogies
startYear = 2
# the last year over which to average climatalogies
endYear = 11

[timeSeries]
## options related to producing time series plots, often to compare against
## observations and previous runs

# start and end years for timeseries analysis. Using out-of-bounds values
#   like start_year = 1 and end_year = 9999 will be clipped to the valid range
#   of years, and is a good way of insuring that all values are used.
startYear = 2
endYear = 10

[index]
## options related to producing nino index.

# start and end years for the nino 3.4 analysis.  Using out-of-bounds values
#   like start_year = 1 and end_year = 9999 will be clipped to the valid range
#   of years, and is a good way of insuring that all values are used.
# For valid statistics, index times should include at least 30 years
startYear = 2
endYear = 11

[streamfunctionMOC]
## options related to plotting the streamfunction of the meridional overturning
## circulation (MOC)

# Use postprocessing script to compute the MOC? You want this to be True
# for low-resolution simulations that use GM to parameterize eddies, because
# the online MOC analysis member currently does not include the bolus velocity
# in its calculation, whereas the postprocessing script does.
# NOTE: this is a temporary option that will be removed once the online
# MOC takes into account the bolus velocity when GM is on.
usePostprocessingScript = True
```

**Comment by chengdang** [comment]
conda list

```
(mpas_analysis) cdang@edison02:~/mpas_analysis/scripts$ conda activate mpas_analysis
(mpas_analysis) cdang@edison02:~/mpas_analysis/scripts$ conda list
# packages in environment at /global/homes/c/cdang/.conda/envs/mpas_analysis:
#
asn1crypto                0.24.0                py37_1003    conda-forge
atk                       2.25.90           hb9dd440_1002    conda-forge
atomicwrites              1.3.0                      py_0    conda-forge
attrs                     18.2.0                     py_0    conda-forge
basemap                   1.1.0            py37h50ae964_7    conda-forge
blas                      1.0                         mkl
bokeh                     1.0.4                 py37_1000    conda-forge
bottleneck                1.2.1           py37h3010b51_1001    conda-forge
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
cairo                     1.16.0            ha4e643d_1000    conda-forge
certifi                   2018.11.29            py37_1000    conda-forge
cffi                      1.12.1           py37h9745a5d_0    conda-forge
cftime                    1.0.3.4         py37h3010b51_1000    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
click                     7.0                        py_0    conda-forge
cloudpickle               0.7.0                      py_0    conda-forge
cmocean                   2.0                        py_0    conda-forge
cryptography              2.5              py37hb7f436b_1    conda-forge
curl                      7.64.0               h646f8bb_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
cytoolz                   0.9.0.1         py37h14c3975_1001    conda-forge
dask                      1.1.1                      py_0    conda-forge
dask-core                 1.1.1                      py_0    conda-forge
dbus                      1.13.0            h4e0c4b3_1000    conda-forge
distributed               1.25.3                   py37_0    conda-forge
esmf                      7.1.0r            hdfb41a0_1003    conda-forge
expat                     2.2.5             hf484d3e_1002    conda-forge
fontconfig                2.13.1            h2176d3f_1000    conda-forge
freetype                  2.9.1             h94bbf69_1005    conda-forge
gdk-pixbuf                2.36.12           h49783d7_1002    conda-forge
geos                      3.6.2                hfc679d8_4    conda-forge
gettext                   0.19.8.1          h9745a5d_1001    conda-forge
glib                      2.58.2            hf63aee3_1001    conda-forge
gobject-introspection     1.58.2          py37h2da5eee_1000    conda-forge
graphite2                 1.3.13            hf484d3e_1000    conda-forge
gsl                       2.4                  h14c3975_4
gstreamer                 1.14.4            h66beb1c_1001    conda-forge
gtk2                      2.24.31           hb68c50a_1001    conda-forge
harfbuzz                  2.3.1                h6824563_0    conda-forge
hdf4                      4.2.13            h9a582f1_1002    conda-forge
hdf5                      1.10.4          nompi_h11e915b_1105    conda-forge
heapdict                  1.0.0                 py37_1000    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.8                   py37_1000    conda-forge
intel-openmp              2019.1                      144
jinja2                    2.10                       py_1    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
kiwisolver                1.0.1           py37h6bb024c_1002    conda-forge
krb5                      1.16.3            hc83ff2d_1000    conda-forge
libcurl                   7.64.0               h01ee5af_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             hf484d3e_1005    conda-forge
libgcc-ng                 7.3.0                hdf63c60_0    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libiconv                  1.15              h14c3975_1004    conda-forge
libnetcdf                 4.6.2             hbdf4f91_1001    conda-forge
libpng                    1.6.36            h84994c4_1000    conda-forge
libssh2                   1.8.0             h1ad7b7a_1003    conda-forge
libstdcxx-ng              7.3.0                hdf63c60_0    conda-forge
libtiff                   4.0.10            h648cc4a_1001    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.8             h143f9aa_1005    conda-forge
libxslt                   1.1.32            h4785a14_1002    conda-forge
locket                    0.2.0                      py_2    conda-forge
lxml                      4.3.1            py37h23eabaa_0    conda-forge
markupsafe                1.1.0           py37h14c3975_1000    conda-forge
matplotlib                3.0.2                 py37_1002    conda-forge
matplotlib-base           3.0.2           py37h167e16e_1002    conda-forge
mkl                       2019.1                      144
mkl_fft                   1.0.10           py37h14c3975_1    conda-forge
mkl_random                1.0.2            py37h637b7d7_2    conda-forge
more-itertools            4.3.0                 py37_1000    conda-forge
mpas_analysis             1.1                        py_0    e3sm
mpi                       1.0                       mpich    conda-forge
mpich                     3.2.1             h1c2f66e_1008    conda-forge
msgpack-python            0.6.1            py37h6bb024c_0    conda-forge
nco                       4.7.8                h7e3d18c_1    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
netcdf-fortran            4.4.5             hea25ff8_1000    conda-forge
netcdf4                   1.4.2           py37had69b76_1001    conda-forge
numpy                     1.15.4           py37h7e9f1db_0
numpy-base                1.15.4           py37hde5b4d6_0
olefile                   0.46                       py_0    conda-forge
openblas                  0.3.3             h9ac9557_1001    conda-forge
openssl                   1.0.2p            h14c3975_1002    conda-forge
packaging                 19.0                       py_0    conda-forge
pandas                    0.24.1           py37hf484d3e_0    conda-forge
pango                     1.40.14           h4ea9474_1004    conda-forge
partd                     0.3.9                      py_0    conda-forge
pcre                      8.41              hf484d3e_1003    conda-forge
pillow                    5.4.1           py37h00a061d_1000    conda-forge
pip                       19.0.2                   py37_0    conda-forge
pixman                    0.34.0            h14c3975_1003    conda-forge
pluggy                    0.8.1                      py_0    conda-forge
progressbar2              3.38.0                     py_1    conda-forge
proj4                     5.2.0             h14c3975_1001    conda-forge
psutil                    5.5.1            py37h14c3975_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
py                        1.7.0                      py_0    conda-forge
pycparser                 2.19                       py_0    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pyparsing                 2.3.1                      py_0    conda-forge
pyproj                    1.9.6           py37hc0953d3_1000    conda-forge
pyqt                      5.6.0           py37h13b7fb3_1008    conda-forge
pyshp                     2.1.0                      py_0    conda-forge
pysocks                   1.6.8                 py37_1002    conda-forge
pytest                    4.2.1                    py37_0    conda-forge
pytest-runner             4.4                        py_0    conda-forge
python                    3.7.1             hd21baee_1000    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
python-utils              2.3.0                      py_1    conda-forge
pytz                      2018.9                     py_0    conda-forge
pyyaml                    3.13            py37h14c3975_1001    conda-forge
qt                        5.6.2             hce4f676_1013    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
requests                  2.21.0                py37_1000    conda-forge
scipy                     1.2.0            py37h7c811a0_0
setuptools                40.8.0                   py37_0    conda-forge
shapely                   1.6.4           py37h0c48222_1000    conda-forge
sip                       4.18.1          py37hf484d3e_1000    conda-forge
six                       1.12.0                py37_1000    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
sqlite                    3.26.0            h67949de_1000    conda-forge
tblib                     1.3.2                      py_1    conda-forge
tk                        8.6.9             h84994c4_1000    conda-forge
toolz                     0.9.0                      py_1    conda-forge
tornado                   5.1.1           py37h14c3975_1000    conda-forge
udunits2                  2.2.27.6          h4e0c4b3_1001    conda-forge
urllib3                   1.24.1                py37_1000    conda-forge
wheel                     0.33.0                   py37_0    conda-forge
xarray                    0.11.3                   py37_0    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.9             h14c3975_1004    conda-forge
xorg-libsm                1.2.3             h4937e3b_1000    conda-forge
xorg-libx11               1.6.7             h14c3975_1000    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.2             h14c3975_1007    conda-forge
xorg-libxext              1.3.3             h14c3975_1004    conda-forge
xorg-libxrender           0.9.10            h14c3975_1002    conda-forge
xorg-libxt                1.1.5             h14c3975_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.1.7             h14c3975_1001    conda-forge
zict                      0.1.3                      py_0    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
```

**Comment by xylar** [comment]
For now, just so you can make progress, I would add `'no_ssh'` to the generate option in your config file.  I'll look into it in the meantime and ask you for permission to try your run if I can't reproduce the error on my own data.

**Comment by xylar** [comment]
Yep, with the latest libraries, I get the same exact error on my laptop so that'll make it easier to fix.  Thank again for reporting this.

**Comment by chengdang** [comment]
Thank you for looking into this.
