### ISSUE TITLE
 ERROR in task mpasTimeSeriesOcean

### ISSUE THREAD

**Issue by chengdang** [MPAS-Dev/MPAS-Analysis#544]
Hi:

I'm trying to run MPAS analysis on edison using MPAS-analysis codebase from git develop branch, and I got the following error:

```
(mpas_analysis) cdang@edison03:~/mpas_analysis/MPAS-Analysis$ python -m mpas_analysis ../scripts/m2o.SNICAR_AD_land_seaice.piControl.ne30_oEC.edison
Running tasks:  40% |#########################################                                                              | ETA:   0:18:07**ERROR in task mpasTimeSeriesOcean.  See log file /global/cscratch1/sd/cdang/acme_scratch/edison/archive/exp.SNICAR_AD_land_seaice.cmip6-picontrol.nodeL/mpas_analysis/logs/mpasTimeSeriesOcean.log for details**
Running tasks:  61% |###############################################################                                        | ETA:   0:09:2^CTraceback (most recent call last):
  File "/global/homes/c/cdang/.conda/envs/mpas_analysis/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/global/homes/c/cdang/.conda/envs/mpas_analysis/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/global/u2/c/cdang/mpas_analysis/MPAS-Analysis/mpas_analysis/__main__.py", line 810, in <module>
    main()
  File "/global/u2/c/cdang/mpas_analysis/MPAS-Analysis/mpas_analysis/__main__.py", line 774, in main
    run_analysis(config, analyses)
  File "/global/u2/c/cdang/mpas_analysis/MPAS-Analysis/mpas_analysis/__main__.py", line 481, in run_analysis
    analysisTask = wait_for_task(runningTasks)
  File "/global/u2/c/cdang/mpas_analysis/MPAS-Analysis/mpas_analysis/__main__.py", line 557, in wait_for_task
    analysisTask.join(timeout=timeout)
  File "/global/homes/c/cdang/.conda/envs/mpas_analysis/lib/python3.7/multiprocessing/process.py", line 140, in join
    res = self._popen.wait(timeout)
  File "/global/homes/c/cdang/.conda/envs/mpas_analysis/lib/python3.7/multiprocessing/popen_fork.py", line 45, in wait
    if not wait([self.sentinel], timeout):
  File "/global/homes/c/cdang/.conda/envs/mpas_analysis/lib/python3.7/multiprocessing/connection.py", line 920, in wait
    ready = selector.select(timeout)
  File "/global/homes/c/cdang/.conda/envs/mpas_analysis/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
Running tasks: 100% |#######################################################################################################| Time:  0:15:18
```

mpasTimeSeriesOcean.log:
```
Computing MPAS time series from first year plus files:
    mpaso.hist.am.timeSeriesStatsMonthly.0002-01-01.nc through
    mpaso.hist.am.timeSeriesStatsMonthly.0011-12-01.nc
running: ncrcat -4 --record_append --no_tmp_fl -v timeMonthly_avg_avgValueWithinOceanLayerRegion_avgLayerTemperature,timeMonthly_avg_avgValueWithinOceanLayerRegion_avgLayerSalinity,timeMonthly_avg_avgValueWithinOceanLayerRegion_sumLayerMaskValue,timeMonthly_avg_avgValueWithinOceanLayerRegion_avgLayerArea,timeMonthly_avg_avgValueWithinOceanLayerRegion_avgLayerThickness,timeMonthly_avg_avgValueWithinOceanRegion_avgSurfaceTemperature,xtime_startMonthly,xtime_endMonthly /global/cscratch1/sd/cdang/acme_scratch/edison/archive/exp.SNICAR_AD_land_seaice.cmip6-picontrol.nodeL//ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0001-01-01.nc ... /global/cscratch1/sd/cdang/acme_scratch/edison/archive/exp.SNICAR_AD_land_seaice.cmip6-picontrol.nodeL//ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0011-12-01.nc /global/cscratch1/sd/cdang/acme_scratch/edison/archive/exp.SNICAR_AD_land_seaice.cmip6-picontrol.nodeL/mpas_analysis/timeseries/mpasTimeSeriesOcean.nc
Process mpasTimeSeriesOcean:
Traceback (most recent call last):
  File "/global/homes/c/cdang/.conda/envs/mpas_analysis/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/global/homes/c/cdang/.conda/envs/mpas_analysis/lib/python3.7/site-packages/mpas_analysis/shared/analysis_task.py", line 324, in run
    raise e
  File "/global/homes/c/cdang/.conda/envs/mpas_analysis/lib/python3.7/site-packages/mpas_analysis/shared/analysis_task.py", line 320, in run
    self.run_task()
  File "/global/homes/c/cdang/.conda/envs/mpas_analysis/lib/python3.7/site-packages/mpas_analysis/shared/time_series/mpas_time_series_task.py", line 232, in run_task
    self._compute_time_series_with_ncrcat()
  File "/global/homes/c/cdang/.conda/envs/mpas_analysis/lib/python3.7/site-packages/mpas_analysis/shared/time_series/mpas_time_series_task.py", line 323, in _compute_time_series_with_ncrcat
    stdout, stderr = process.communicate()
  File "/global/homes/c/cdang/.conda/envs/mpas_analysis/lib/python3.7/subprocess.py", line 933, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/global/homes/c/cdang/.conda/envs/mpas_analysis/lib/python3.7/subprocess.py", line 1675, in _communicate
    ready = selector.select(timeout)
  File "/global/homes/c/cdang/.conda/envs/mpas_analysis/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt

Computing MPAS time series from first year plus files:
    mpaso.hist.am.timeSeriesStatsMonthly.0002-01-01.nc through
    mpaso.hist.am.timeSeriesStatsMonthly.0011-12-01.nc
analysis task mpasTimeSeriesOcean failed during run
Traceback (most recent call last):
  File "/global/u2/c/cdang/mpas_analysis/MPAS-Analysis/mpas_analysis/shared/analysis_task.py", line 320, in run
    self.run_task()
  File "/global/u2/c/cdang/mpas_analysis/MPAS-Analysis/mpas_analysis/shared/time_series/mpas_time_series_task.py", line 232, in run_task
    self._compute_time_series_with_ncrcat()
  File "/global/u2/c/cdang/mpas_analysis/MPAS-Analysis/mpas_analysis/shared/time_series/mpas_time_series_task.py", line 283, in _compute_time_series_with_ncrcat
    lastDate = dates[-1]
IndexError: list index out of range

Execution time: 0:00:00.14
```

Here is the config file m2o.SNICAR_AD_land_seaice.piControl.ne30_oEC.edison:

```
[runs]
## options related to the run to be analyzed and control runs to be
## compared against

# mainRunName is a name that identifies the simulation being analyzed.
mainRunName = exp.SNICAR_AD_land_seaice.cmip6-picontrol.nodeL

# config file for a control run to which this run will be compared.  The
# analysis should have already been run to completion once with this config
# file, so that the relevant MPAS climatologies already exist and have been
# remapped to the comparison grid.  Leave this option commented out if no
# control run is desired.
# controlRunConfigFile = /path/to/config/file

# config file for a main run on which the analysis was already run to
# completion.  The relevant MPAS climatologies already exist and have been
# remapped to the comparison grid and time series have been extracted.
# Leave this option commented out if the analysis for the main run should be
# performed.
# mainRunConfigFile = /path/to/config/file

[execute]
## options related to executing parallel tasks

# the number of parallel tasks (1 means tasks run in serial, the default)
parallelTaskCount = 4

# the parallelism mode in ncclimo ("serial" or "bck")
# Set this to "bck" (background parallelism) if running on a machine that can
# handle 12 simultaneous processes, one for each monthly climatology.
ncclimoParallelMode = bck

[diagnostics]
## config options related to observations, mapping files and region files used
## by MPAS-Analysis in diagnostics computations.

# The base path to the diagnostics directory.  Typically, this will be a shared
# directory on each E3SM supported machine (see the example config files for
# its location).  For other machines, this would be the directory pointed to
# when running "download_analysis_data.py" to get the public observations,
# mapping files and region files.
baseDirectory = /global/project/projectdirs/acme/diagnostics

[input]
## options related to reading in the results to be analyzed

# directory containing model results
baseDirectory = /global/cscratch1/sd/cdang/acme_scratch/edison/archive/exp.SNICAR_AD_land_seaice.cmip6-picontrol.nodeL/

# subdirectory containing restart files
runSubdirectory = run
# subdirectory for ocean history files
oceanHistorySubdirectory = ocn/hist
# subdirectory for sea ice history files
seaIceHistorySubdirectory = ice/hist

# names of ocean and sea ice meshes (e.g. oEC60to30v3, oQU240v3, oRRS30to10v3, etc.)
mpasMeshName = oEC60to30v3

# names of namelist and streams files, either a path relative to baseDirectory
# or an absolute path.
oceanNamelistFileName = run/mpaso_in
oceanStreamsFileName = run/streams.ocean
seaIceNamelistFileName = run/mpassi_in
seaIceStreamsFileName = run/streams.seaice

[output]
## options related to writing out plots, intermediate cached data sets, logs,
## etc.

# directory where analysis should be written
baseDirectory = /global/cscratch1/sd/cdang/acme_scratch/edison/archive/exp.SNICAR_AD_land_seaice.cmip6-picontrol.nodeL/mpas_analysis

# provide an absolute path to put HTML in an alternative location (e.g. a web
# portal)
# htmlSubdirectory = global/project/projectdirs/acme/www/USERNAME/RUNNAME
htmlSubdirectory = /global/project/projectdirs/m2833/www/cdang/mpas_analysis.m2o.SNICAR_AD_land_seaice.piControl.ne30_oEC.edison

# a list of analyses to generate.  Valid names can be seen by running:
#   mpas_analysis --list
# This command also lists tags for each analysis.
# Shortcuts exist to generate (or not generate) several types of analysis.
# These include:
#   'all' -- all analyses will be run
#   'all_<tag>' -- all analysis with a particular tag will be run
#   'all_<component>' -- all analyses from a given component (either 'ocean'
#                        or 'seaIce') will be run
#   'only_<component>', 'only_<tag>' -- all analysis from this component or
#                                       with this tag will be run, and all
#                                       analysis for other components or
#                                       without the tag will be skipped
#   'no_<task_name>' -- skip the given task
#   'no_<component>', 'no_<tag>' -- in analogy to 'all_*', skip all analysis
#                                   tasks from the given compoonent or with
#                                   the given tag.  Do
#                                      mpas_analysis --list
#                                   to list all task names and their tags
# an equivalent syntax can be used on the command line to override this
# option:
#    mpas_analysis config.analysis --generate \
#         all,no_ocean,all_timeSeries
# All tasks with tag "landIceCavities" are disabled because this run did not
# include land-ice cavities.
generate = ['all', 'no_landIceCavities', 'no_eke', 'no_BGC', 'no_icebergs', 'no_ssh']

[climatology]
## options related to producing climatologies, typically to compare against
## observations and previous runs

# the first year over which to average climatalogies
startYear = 2
# the last year over which to average climatalogies
endYear = 11

[timeSeries]
## options related to producing time series plots, often to compare against
## observations and previous runs

# start and end years for timeseries analysis. Using out-of-bounds values
#   like start_year = 1 and end_year = 9999 will be clipped to the valid range
#   of years, and is a good way of insuring that all values are used.
startYear = 2
endYear = 11

[index]
## options related to producing nino index.


# start and end years for the nino 3.4 analysis.  Using out-of-bounds values
#   like start_year = 1 and end_year = 9999 will be clipped to the valid range
#   of years, and is a good way of insuring that all values are used.
# For valid statistics, index times should include at least 30 years
startYear = 2
endYear = 11

[streamfunctionMOC]
## options related to plotting the streamfunction of the meridional overturning
## circulation (MOC)

# Use postprocessing script to compute the MOC? You want this to be True
# for low-resolution simulations that use GM to parameterize eddies, because
# the online MOC analysis member currently does not include the bolus velocity
# in its calculation, whereas the postprocessing script does.
# NOTE: this is a temporary option that will be removed once the online
# MOC takes into account the bolus velocity when GM is on.
usePostprocessingScript = True
```

May I have some suggestions on how to solve this? Thanks a lot.

**Comment by xylar** [comment]
@chengdang, thank you for reporting this issue.  I think I can help.

I think what you pointed out is an odd case that might technically be considered a bug but probably not one I'm going to take the time to fix.

I can tell from the log file that you rant the analysis once and then killed it part way through.  I do that a lot of the time, too, but it's not a safe thing to do unless you `--purge` the results as part of your next run.  That will clean everything up and make sure no half-written files are left behind.  In your case, you ran again without `--purge` and an empty time series file was left behind somehow (at least that's what the log seems to suggest).  The code isn't prepared to have a time series file that has all the variables it needs but no time entries (I'm not sure how this happened, actually) so it doesn't bother to check if there are no time entries in the file, or to clean up the corrupted file if so.  You need to do this yourself or `--purge` the whole analysis output and start over.

I bet if you run again with:
```
python -m mpas_analysis ../scripts/m2o.SNICAR_AD_land_seaice.piControl.ne30_oEC.edison --purge
```
everything will work okay.  Let me know if that's not the case.

**Comment by chengdang** [comment]
@xylar Thank you! I know it must be something I missed since I was able to run the simulation. Everything is okay now. I'll close the issue. Thanks again.
