### ISSUE TITLE
Failure in ocean regions create mask

### ISSUE THREAD

**Issue by vanroekel** [MPAS-Dev/MPAS-Analysis#619]
I'm trying to run mpas-analysis on the new CONUS b-case run.  Most everything works, but in the oceanRegions analysis, I see the following error.
```
analysis task oceanRegionalProfiles_computeRegionMasks failed during run 
Traceback (most recent call last):
  File "/lcrc/group/acme/lvanroe/MPAS-Analysis/mpas_analysis/shared/analysis_task.py", line 328, in run
    self.run_task()
  File "/lcrc/group/acme/lvanroe/MPAS-Analysis/mpas_analysis/shared/regions/compute_region_masks_subtask.py", line 338, in run_task
    self.subprocessCount, showProgress=False)
  File "/lcrc/group/acme/lvanroe/MPAS-Analysis/mpas_analysis/shared/regions/compute_region_masks_subtask.py", line 164, in compute_region_masks
    dsMasks[propertyName] = (('nRegions'), properties[propertyName])
  File "/lcrc/soft/climate/e3sm-unified/base/envs/e3sm_unified_1.2.6/lib/python3.7/site-packages/xarray/core/dataset.py", line 1122, in __setitem__
    self.update({key: value})
  File "/lcrc/soft/climate/e3sm-unified/base/envs/e3sm_unified_1.2.6/lib/python3.7/site-packages/xarray/core/dataset.py", line 3035, in update
    variables, coord_names, dims = dataset_update_method(self, other)
  File "/lcrc/soft/climate/e3sm-unified/base/envs/e3sm_unified_1.2.6/lib/python3.7/site-packages/xarray/core/merge.py", line 626, in dataset_update_method
    indexes=dataset.indexes)
  File "/lcrc/soft/climate/e3sm-unified/base/envs/e3sm_unified_1.2.6/lib/python3.7/site-packages/xarray/core/merge.py", line 465, in merge_core
    dims = calculate_dimensions(variables)
  File "/lcrc/soft/climate/e3sm-unified/base/envs/e3sm_unified_1.2.6/lib/python3.7/site-packages/xarray/core/dataset.py", line 129, in calculate_dimensions
    (dim, size, k, dims[dim], last_used[dim]))
ValueError: conflicting sizes for dimension 'nRegions': length 6 on 'constituents' and length 9 on 'regionCellMasks'

```
My config file is here 
```
/lcrc/group/acme/lvanroe/MPAS-Analysis/config.A_WCYC1850_ne30_oNAEC60to30cr8L60v1_anvil02
```
This is with the latest e3sm-unified.

**Comment by xylar** [comment]
@vanroekel, first, I will build all the CONUS masks and put them in the diagnostics directories on all supported machines as soon as I can.  I'll also look into this error as soon as I'm able.  This may not happen until late next week, I'm afraid.

**Comment by xylar** [comment]
@vanroekel, I'm finally getting to this.  I'm able to reproduce the problem and I'm looking into a solution.
