### ISSUE TITLE
Remapping of EKE obs failing on compy

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#621]
The task `climatologyMapEKE_remapObservations` is failing with:
```
running: ncremap -i /compyfs/zhan429/processflow/piCtl_cold_try1_short_mpas-analysis/output/diags/piCtl_cold/mpas_analysis/0001_0005_vs_obs/clim/obs/eke_0.25x0.25degree_ANN.nc -m /compyfs/zhan429/processflow/piCtl_cold_try1_short_mpas-analysis/output/diags/piCtl_cold/mpas_analysis/0001_0005_vs_obs/mapping/map_obs_eke_0.25x0.25degree_to_0.5x0.5degree_bilinear.nc --vrb=1 -o /compyfs/zhan429/processflow/piCtl_cold_try1_short_mpas-analysis/output/diags/piCtl_cold/mpas_analysis/0001_0005_vs_obs/clim/obs/remapped/eke_0.25x0.25degree_to_0.5x0.5degree_ANN.nc -R --renormalize=0.01 --rgr lat_nm=Lat --rgr lon_nm=Lon --rgr lat_nm_out=lat --rgr lon_nm_out=lon
Input #00: /compyfs/zhan429/processflow/piCtl_cold_try1_short_mpas-analysis/output/diags/piCtl_cold/mpas_analysis/0001_0005_vs_obs/clim/obs/eke_0.25x0.25degree_ANN.nc
Map/Wgt  : /compyfs/zhan429/processflow/piCtl_cold_try1_short_mpas-analysis/output/diags/piCtl_cold/mpas_analysis/0001_0005_vs_obs/mapping/map_obs_eke_0.25x0.25degree_to_0.5x0.5degree_bilinear.nc
ncks: ERROR nco_malloc() unable to allocate 18446744056529682440 B = 18446744056529682 kB = 18446744056529 MB = 18446744056 GB
ncks: INFO NCO has reported a malloc() failure. malloc() failures usually indicate that your machine has less free memory (RAM+swap) than the requested amount. As such, malloc() failures result from the physical limitations imposed by your hardware. Read http://nco.sf.net/nco.html#mmr for a description of NCO memory usage. The likeliest case is that this problem is caused by inadequate RAM on your system, and is not an NCO bug. If so, there are two potential workarounds: First is to process your data in smaller chunks, e.g., smaller or more hyperslabs. The second is to use a machine with more free memory, so that malloc() succeeds. NB: Operating on compressed netCDF4 data can easily consume more RAM than expected or mentioned in the NCO documentation.

ncremap: ERROR Failed to regrid. cmd_rgr[0] failed. Debug this:
 ncks -O -t 2 --no_tmp_fl --gaa remap_script=ncremap --gaa remap_command="'/qfs/people/zhan429/.conda/envs/mpas-analysis/bin/ncremap -i /compyfs/zhan429/processflow/piCtl_cold_try1_short_mpas-analysis/output/diags/piCtl_cold/mpas_analysis/0001_0005_vs_obs/clim/obs/eke_0.25x0.25degree_ANN.nc -m /compyfs/zhan429/processflow/piCtl_cold_try1_short_mpas-analysis/output/diags/piCtl_cold/mpas_analysis/0001_0005_vs_obs/mapping/map_obs_eke_0.25x0.25degree_to_0.5x0.5degree_bilinear.nc --vrb=1 -o /compyfs/zhan429/processflow/piCtl_cold_try1_short_mpas-analysis/output/diags/piCtl_cold/mpas_analysis/0001_0005_vs_obs/clim/obs/remapped/eke_0.25x0.25degree_to_0.5x0.5degree_ANN.nc -R --renormalize=0.01 --rgr lat_nm=Lat --rgr lon_nm=Lon --rgr lat_nm_out=lat --rgr lon_nm_out=lon'" --gaa remap_hostname=compy-e.pnl.gov --gaa remap_version=4.8.1 --hdr_pad=10000    --renormalize=0.01 --rgr lat_nm=Lat --rgr lon_nm=Lon --rgr lat_nm_out=lat --rgr lon_nm_out=lon --map="/compyfs/zhan429/processflow/piCtl_cold_try1_short_mpas-analysis/output/diags/piCtl_cold/mpas_analysis/0001_0005_vs_obs/mapping/map_obs_eke_0.25x0.25degree_to_0.5x0.5degree_bilinear.nc" "/compyfs/zhan429/processflow/piCtl_cold_try1_short_mpas-analysis/output/diags/piCtl_cold/mpas_analysis/0001_0005_vs_obs/clim/obs/eke_0.25x0.25degree_ANN.nc" "/compyfs/zhan429/processflow/piCtl_cold_try1_short_mpas-analysis/output/diags/piCtl_cold/mpas_analysis/0001_0005_vs_obs/clim/obs/remapped/eke_0.25x0.25degree_to_0.5x0.5degree_ANN.nc"
  
analysis task climatologyMapEKE_remapObservations failed during run
Traceback (most recent call last):
  File "/qfs/people/zhan429/.conda/envs/mpas-analysis/lib/python3.7/site-packages/mpas_analysis/shared/analysis_task.py", line 328, in run
    self.run_task()
  File "/qfs/people/zhan429/.conda/envs/mpas-analysis/lib/python3.7/site-packages/mpas_analysis/shared/climatology/remap_observed_climatology_subtask.py", line 191, in run_task
    logger=self.logger)
  File "/qfs/people/zhan429/.conda/envs/mpas-analysis/lib/python3.7/site-packages/mpas_analysis/shared/climatology/climatology.py", line 345, in remap_and_write_climatology
    logger=logger)
  File "/qfs/people/zhan429/.conda/envs/mpas-analysis/lib/python3.7/site-packages/mpas_analysis/shared/interpolation/remapper.py", line 362, in remap_file
    ' '.join(args))
subprocess.CalledProcessError: Command 'ncremap -i /compyfs/zhan429/processflow/piCtl_cold_try1_short_mpas-analysis/output/diags/piCtl_cold/mpas_analysis/0001_0005_vs_obs/clim/obs/eke_0.25x0.25degree_ANN.nc -m /compyfs/zhan429/processflow/piCtl_cold_try1_short_mpas-analysis/output/diags/piCtl_cold/mpas_analysis/0001_0005_vs_obs/mapping/map_obs_eke_0.25x0.25degree_to_0.5x0.5degree_bilinear.nc --vrb=1 -o /compyfs/zhan429/processflow/piCtl_cold_try1_short_mpas-analysis/output/diags/piCtl_cold/mpas_analysis/0001_0005_vs_obs/clim/obs/remapped/eke_0.25x0.25degree_to_0.5x0.5degree_ANN.nc -R --renormalize=0.01 --rgr lat_nm=Lat --rgr lon_nm=Lon --rgr lat_nm_out=lat --rgr lon_nm_out=lon' returned non-zero exit status 1.
```
There may be some sort of a bug in the mapping file or in `ncreamp`, and this deserves further investigation.

**Comment by xylar** [comment]
I was able to run `climatologyMapEKE` without any issues on the example run on compy.  I think this issue has either been fixed by updating the diagnostics or was specific to the run that @chengzhuzhang was testing.  I'm closing for now but please reopen if the issue recurs.
