### ISSUE TITLE
Update to `config_use_GM` in streamfunctionMOC when Redi changes are in

### ISSUE THREAD

**Issue by milenaveneziani** [MPAS-Dev/MPAS-Analysis#674]
With the new changes to GM config name options (Redi PR#280 in MPAS-Model), we will have to change from `config_use_standardgm` to `config_use_GM` in `streamfunctionMOC.py`.
We'll probably want to be backward compatible for a while, otherwise we won't be able to process v1 model output.

**Comment by xylar** [comment]
@milenaveneziani, this is the error, right?  We need to fix this soon or the MOC will stop being part of our output.
```
Traceback (most recent call last):
  File "/global/u2/x/xylar/mpas_work/analysis/fix_simulation_start_time/mpas_analysis/__main__.py", line 373, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/global/u2/x/xylar/mpas_work/analysis/fix_simulation_start_time/mpas_analysis/ocean/streamfunction_moc.py", line 279, in setup_and_check
    self.includeBolus = self.namelist.getbool('config_use_standardgm')
  File "/global/u2/x/xylar/mpas_work/analysis/fix_simulation_start_time/mpas_analysis/shared/io/namelist_streams_interface.py", line 225, in getbool
    if 'True' in self.nml[key.lower()] or 'true' in self.nml[key.lower()]:
  File "/global/u2/x/xylar/mpas_work/analysis/fix_simulation_start_time/mpas_analysis/shared/containers.py", line 36, in __getitem__
    return self._data[key]
KeyError: 'config_use_standardgm'
Warning: streamfunctionMOC: computeMOCClimatology failed during check and will not be run
Warning: subtask of streamfunctionMOC failed during check, so this task will not be run
```

**Comment by milenaveneziani** [comment]
yes, exactly.
The fix is really simple, I have just forgotten. I'll do it later today.

**Comment by xylar** [comment]
I think I've got it.  I'll push a fix in a few minutes if it works.
