### ISSUE TITLE
MLD analysis not working with latest xarray

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#687]
During "setup-and-check" stage:

```
Traceback (most recent call last):
  File "/global/u2/x/xylar/mpas_work/analysis/mpas_analysis/mpas_analysis/__main__.py", line 372, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/global/u2/x/xylar/mpas_work/analysis/mpas_analysis/mpas_analysis/shared/climatology/remap_observed_climatology_subtask.py", line 125, in setup_and_check
    self._setup_remappers(self.fileName)
  File "/global/u2/x/xylar/mpas_work/analysis/mpas_analysis/mpas_analysis/shared/climatology/remap_observed_climatology_subtask.py", line 333, in _setup_remappers
    obsDescriptor = self.get_observation_descriptor(fileName)
  File "/global/u2/x/xylar/mpas_work/analysis/mpas_analysis/mpas_analysis/ocean/climatology_map_mld.py", line 201, in get_observation_descriptor
    dsObs = self.build_observational_dataset(fileName)
  File "/global/u2/x/xylar/mpas_work/analysis/mpas_analysis/mpas_analysis/ocean/climatology_map_mld.py", line 234, in build_observational_dataset
    dsObs.iMONTH.values += 1
  File "/global/homes/x/xylar/miniconda2/envs/mpas_analysis_py3.7/lib/python3.7/site-packages/xarray/core/common.py", line 262, in __setattr__
    object.__setattr__(self, name, value)
  File "/global/homes/x/xylar/miniconda2/envs/mpas_analysis_py3.7/lib/python3.7/site-packages/xarray/core/dataarray.py", line 562, in values
    self.variable.values = value
  File "/global/homes/x/xylar/miniconda2/envs/mpas_analysis_py3.7/lib/python3.7/site-packages/xarray/core/variable.py", line 2115, in values
    f"Cannot assign to the .values attribute of dimension coordinate a.k.a IndexVariable {self.name!r}. "
ValueError: Cannot assign to the .values attribute of dimension coordinate a.k.a IndexVariable 'iMONTH'. Please use DataArray.assign_coords, Dataset.assign_coords or Dataset.assign as appropriate.
Warning: climatologyMapMLD: remapObservations failed during check and will not be run
Warning: subtask of climatologyMapMLD failed during check, so this task will not be run
```

**Comment by xylar** [comment]
Looks like an easy fix.
