### ISSUE TITLE
simulationStartTime not being read in

### ISSUE THREAD

**Issue by darincomeau** [MPAS-Dev/MPAS-Analysis#704]
The following error is appearing, causing some (but not all) time series tasks to not run:

``` 
File "/global/project/projectdirs/m3412/dcomeau/mpas_analysis_repos/develop/MPAS-Analysis/mpas_analysis/shared/timekeeping/utility.py", line 64, in get_simulation_start_time
    simulationStartTime = ''.join(simulationStartTime.astype('U')).strip()
TypeError: sequence item 19: expected str instance, MaskedConstant found
```

The analysis is run off current ```develop``` (hash 3e700c2).

The simulations on which this occurs were branched off master on May 29, 2020 (E3SM hash ```be8d6eadf```, PR https://github.com/E3SM-Project/E3SM/pull/3526). The mpas-source hash is ```bdf772aa```; the latest ```ocean/develop``` merge into ```e3sm/develop``` for this hash is (https://github.com/MPAS-Dev/MPAS-Model/commit/9073cafe01e06d7b489656d40d72a905bec4dde2).

Perhaps overkill information, but I've been trying to track down recent changes that could point to the error.

tagging @stephenprice who has also seen this error.

**Comment by xylar** [comment]
@darincomeau and @milenaveneziani, this is almost certainly related to the recent switch from PIO1 to PIO2 (scorpio-classic to scorpio).  Strings seem to be getting null characters `\x00` when read in by `netcdf4` (and maybe `xarray`, though maybe not).  I'll look into this but here's a related issue for the paraview extractor:
https://github.com/MPAS-Dev/MPAS-Tools/issues/317

**Comment by xylar** [comment]
I can probably fix this next week but probably not today.

**Comment by xylar** [comment]
This code is using `netcdf4`, which confirms my suspicion that `xarray` may be fine with these strings with extra NULL characters but `netcdf4` is not:
https://github.com/MPAS-Dev/MPAS-Analysis/blob/develop/mpas_analysis/shared/timekeeping/utility.py#L61-L65

I think the easiest would be to modify this code to use `xarray` instead.

**Comment by xylar** [comment]
Could you see if #705 fixes this?

**Comment by darincomeau** [comment]
Thanks @xylar for looking into this (but no more until next week!). With #705 , I'm getting a different error:
```
Traceback (most recent call last):
  File "/global/project/projectdirs/m3412/dcomeau/mpas_analysis_repos/develop/MPAS-Analysis/mpas_analysis/__main__.py", line 373, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/global/project/projectdirs/m3412/dcomeau/mpas_analysis_repos/develop/MPAS-Analysis/mpas_analysis/shared/time_series/mpas_time_series_task.py", line 203, in setup_and_check
    firstYearInputFiles = self.historyStreams.readpath(
  File "/global/project/projectdirs/m3412/dcomeau/mpas_analysis_repos/develop/MPAS-Analysis/mpas_analysis/shared/io/namelist_streams_interface.py", line 444, in readpath
    startDate = string_to_datetime(startDate)
  File "/global/project/projectdirs/m3412/dcomeau/mpas_analysis_repos/develop/MPAS-Analysis/mpas_analysis/shared/timekeeping/utility.py", line 113, in string_to_datetime
    _parse_date_string(dateString, isInterval=False)
  File "/global/project/projectdirs/m3412/dcomeau/mpas_analysis_repos/develop/MPAS-Analysis/mpas_analysis/shared/timekeeping/utility.py", line 462, in _parse_date_string
    = [int(sub) for sub in hms.split(':')]
  File "/global/project/projectdirs/m3412/dcomeau/mpas_analysis_repos/develop/MPAS-Analysis/mpas_analysis/shared/timekeeping/utility.py", line 462, in <listcomp>
    = [int(sub) for sub in hms.split(':')]
ValueError: invalid literal for int() with base 10: '00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
```

**Comment by xylar** [comment]
@darincomeau, I'm getting back to this now.  Hopefully, I'll be able to fix it tonight.
