### ISSUE TITLE
HDF5 errors on cori haswell

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#711]
When I try to run analysis on cori haswell, I'm seeing errors like:
```
$ python -m mpas_analysis configs/polarRegions.conf config.20190923.GMPAS-IAF.T62_oEC60to30v3wLI.cori-knl --purge --verbose

  File "/global/homes/x/xylar/miniconda2/envs/mpas-analysis/lib/python3.8/site-packages/xarray/backends/file_manager.py", line 198, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/global/homes/x/xylar/miniconda2/envs/mpas-analysis/lib/python3.8/site-packages/xarray/backends/lru_cache.py", line 53, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/global/cfs/cdirs/e3sm/diagnostics/observations/Ocean/SOSE/SOSE_2005-2010_monthly_pot_temp_6000.0x6000.0km_10.0km_Antarctic_stereo_20180710.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False))]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/global/u2/x/xylar/mpas_work/analysis/rename_ross_regions/mpas_analysis/__main__.py", line 373, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/global/u2/x/xylar/mpas_work/analysis/rename_ross_regions/mpas_analysis/shared/climatology/remap_observed_climatology_subtask.py", line 125, in setup_and_check
    self._setup_remappers(self.fileName)
  File "/global/u2/x/xylar/mpas_work/analysis/rename_ross_regions/mpas_analysis/shared/climatology/remap_observed_climatology_subtask.py", line 333, in _setup_remappers
    obsDescriptor = self.get_observation_descriptor(fileName)
  File "/global/u2/x/xylar/mpas_work/analysis/rename_ross_regions/mpas_analysis/ocean/remap_sose_climatology.py", line 117, in get_observation_descriptor
    obsDescriptor = ProjectionGridDescriptor.read(
  File "/global/homes/x/xylar/miniconda2/envs/mpas-analysis/lib/python3.8/site-packages/pyremap/descriptor.py", line 628, in read
    ds = xarray.open_dataset(fileName)
  File "/global/homes/x/xylar/miniconda2/envs/mpas-analysis/lib/python3.8/site-packages/xarray/backends/api.py", line 501, in open_dataset
    store = backends.NetCDF4DataStore.open(
  File "/global/homes/x/xylar/miniconda2/envs/mpas-analysis/lib/python3.8/site-packages/xarray/backends/netCDF4_.py", line 358, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/global/homes/x/xylar/miniconda2/envs/mpas-analysis/lib/python3.8/site-packages/xarray/backends/netCDF4_.py", line 314, in __init__
    self.format = self.ds.data_model
  File "/global/homes/x/xylar/miniconda2/envs/mpas-analysis/lib/python3.8/site-packages/xarray/backends/netCDF4_.py", line 367, in ds
    return self._acquire()
  File "/global/homes/x/xylar/miniconda2/envs/mpas-analysis/lib/python3.8/site-packages/xarray/backends/netCDF4_.py", line 361, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/global/homes/x/xylar/miniconda2/envs/mpas-analysis/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/global/homes/x/xylar/miniconda2/envs/mpas-analysis/lib/python3.8/site-packages/xarray/backends/file_manager.py", line 186, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/global/homes/x/xylar/miniconda2/envs/mpas-analysis/lib/python3.8/site-packages/xarray/backends/file_manager.py", line 204, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "netCDF4/_netCDF4.pyx", line 2321, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4/_netCDF4.pyx", line 1885, in netCDF4._netCDF4._ensure_nc_success
OSError: [Errno -101] NetCDF: HDF error: b'/global/cfs/cdirs/e3sm/diagnostics/observations/Ocean/SOSE/SOSE_2005-2010_monthly_pot_temp_6000.0x6000.0km_10.0km_Antarctic_stereo_20180710.nc'
```
The same problem can be seen with `ncdump`:
```
$ ncdump -h /global/cfs/cdirs/e3sm/diagnostics/observations/Ocean/SOSE/SOSE_ANN_T_S_z_vol_SouthernOcean_0.167x0.167degree_20200514.nc 
ncdump: /global/cfs/cdirs/e3sm/diagnostics/observations/Ocean/SOSE/SOSE_ANN_T_S_z_vol_SouthernOcean_0.167x0.167degree_20200514.nc: /global/cfs/cdirs/e3sm/diagnostics/observations/Ocean/SOSE/SOSE_ANN_T_S_z_vol_SouthernOcean_0.167x0.167degree_20200514.nc: NetCDF: HDF error
```

This isn't necessarily an MPAS-Analysis problem but certainly affects our ability to perform analysis on Cori.

**Comment by xylar** [comment]
There is no problem with `ncdump` on the login nodes, so I don't think it's a problem with the files themselves.

**Comment by xylar** [comment]
It seems that converting the `SOSE` files to NetCDF classic 64-bit fixes the issue.  On a login node:
```
ncks -6 SOSE_2005-2010_monthly_pot_temp_SouthernOcean_0.167x0.167degree_20180710.nc test.nc
```
Then, on a Cori Haswell compute node:
```
ncdump -h test.nc
```
```

**Comment by xylar** [comment]
@sbrus89, this seems like it's the same problem we saw on Cori with your bathymetry file.  Did you ever make any headway on what was causing it?  Or did you just do the conversion above and call it a day?

**Comment by sbrus89** [comment]
@xylar, This does seem similar. I believe I just did the conversion and moved on. Do you have any other ideas on what may be causing it?

**Comment by xylar** [comment]
The fixed for me turns out to be the good old:
```
export HDF5_USE_FILE_LOCKING=FALSE
```
Which I normally do, but forgot when I was running interactively.
